---
image: malston/concourse
imageTag: 6.3-ubuntu
postgresql:
  image:
    registry: docker.io
    repository: malston/postgres
    tag: 0.0.2
web:
  ingress:
    enabled: true
    hosts: [concourse.haas-423.pez.vmware.com]
  service:
    api:
      type: LoadBalancer
      loadBalancerIP: 10.213.249.68
  workerGateway:
    type: LoadBalancer
    loadBalancerIP: 10.213.249.68
concourse:
  web:
    externalUrl: http://concourse.haas-423.pez.vmware.com