apiVersion: run.tanzu.vmware.com/v1alpha1       #TKG API endpoint
kind: TanzuKubernetesCluster                    #required parameter
metadata:
  name: tkg-cluster-1                           #cluster name, user defined
  namespace: ns1                                #supervisor namespace
spec:
  distribution:
    version: v1.17                              #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                  #number of control plane nodes
      class: best-effort-small                  #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy #storageclass for control plane
    workers:
      count: 3                                  #number of worker nodes
      class: best-effort-small                  #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy #storageclass for worker nodes
  # settings:
  #   network:
  #     cni:
  #       name: calico
  #     services:
  #       cidrBlocks: ["198.51.100.0/12"]        #Cannot overlap with Supervisor Cluster
  #     pods:
  #       cidrBlocks: ["10.244.0.0/20"]          #Cannot overlap with Supervisor Cluster
  #   storage:
  #     classes: ["gold", "silver"]              #Named PVC storage classes
  #     defaultClass: silver                     #Default PVC storage class