---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/k8s-mgmt
    tag: 0.0.2

inputs:
  - name: repo
  - name: pks-config

params:
  CLUSTER:
  PKS_PASSWORD:

run:
  path: repo/tasks/upgrade-cluster/task.sh
