product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pks_api_certificate))
      private_key_pem: ((pks_api_private_key))
  .properties.cloud_provider:
    selected_option: vsphere
    value: vSphere
  .properties.cloud_provider.vsphere.vcenter_dc:
    value: Datacenter
  .properties.cloud_provider.vsphere.vcenter_ds:
    value: LUN01
  .properties.cloud_provider.vsphere.vcenter_ip:
    value: vcsa-01.haas-439.pez.vmware.com
  .properties.cloud_provider.vsphere.vcenter_master_creds:
    value:
      identity: administrator@vsphere.local
      password: ((vcenter_password))
  .properties.cloud_provider.vsphere.vcenter_vms:
    value: bosh_vms
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    selected_option: nsx
    value: nsx
  .properties.network_selector.nsx.cloud-config-dns:
    value: 10.192.2.10,10.192.2.11
  .properties.network_selector.nsx.floating-ip-pool-ids:
    value: ((nsx_floating_ip_pool_id))
  .properties.network_selector.nsx.ip-block-id:
    value: ((nsx_pods_ip_block_id))
  .properties.network_selector.nsx.nat_mode:
    value: true
  .properties.network_selector.nsx.ncp-ha-heartbeat-period:
    value: 6
  .properties.network_selector.nsx.ncp-ha-master-timeout:
    value: 18
  .properties.network_selector.nsx.ncp-ha-update-timeout:
    value: 12
  .properties.network_selector.nsx.network_automation:
    value: true
  .properties.network_selector.nsx.nodes-ip-block-id:
    value: ((nsx_nodes_ip_block_id))
  .properties.network_selector.nsx.nsx-t-ca-cert:
    value: ((nsx_cert_root_ca))
  .properties.network_selector.nsx.nsx-t-host:
    value: nsxmgr-01.haas-439.pez.vmware.com
  .properties.network_selector.nsx.nsx-t-insecure:
    value: false
  .properties.network_selector.nsx.nsx-t-superuser-certificate:
    value:
      cert_pem: ((nsx_superuser_cert_public_key))
      private_key_pem: ((nsx_superuser_cert_private_key))
  .properties.network_selector.nsx.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.network_selector.nsx.t0-router-id:
    value: ((nsx_t0_router_id))
  .properties.network_selector.nsx.vcenter_cluster:
    value: Cluster
  .properties.node_exporter_deploy:
    value: false
  .properties.oidc_selector:
    selected_option: disabled
    value: disabled
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks-vrops:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: api.pks.haas-439.pez.vmware.com
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.allow_privileged_containers:
    value: true
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_az_placement:
    value:
    - pks-az1
    - pks-az2
    - pks-az3
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - pks-az1
    - pks-az2
    - pks-az3
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan2_selector:
    selected_option: active
    value: Plan Active
  .properties.plan2_selector.active.addons_spec:
    value: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: istio-user
        namespace: default
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: istio-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: istio-user
        namespace: default
      ---
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: install-istio
      spec:
        template:
          spec:
            containers:
            - name: install-istio
              image: pivotalpez/istio-deployer:v1
            serviceAccountName: istio-user
            restartPolicy: Never
        backoffLimit: 4
  .properties.plan2_selector.active.allow_privileged_containers:
    value: true
  .properties.plan2_selector.active.description:
    value: This plan will configure a lightweight kubernetes cluster with Istio installed
  .properties.plan2_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan2_selector.active.kubelet_drain_force:
    value: true
  .properties.plan2_selector.active.kubelet_drain_force_node:
    value: true
  .properties.plan2_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan2_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan2_selector.active.kubelet_drain_timeout:
    value: 15
  .properties.plan2_selector.active.master_az_placement:
    value:
    - pks-az1
    - pks-az2
    - pks-az3
  .properties.plan2_selector.active.master_instances:
    value: 1
  .properties.plan2_selector.active.max_worker_instances:
    value: 50
  .properties.plan2_selector.active.name:
    value: small-Istio
  .properties.plan2_selector.active.worker_az_placement:
    value:
    - pks-az1
    - pks-az2
    - pks-az3
  .properties.plan2_selector.active.worker_instances:
    value: 3
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan11_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan12_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan13_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telegraf_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    selected_option: demo_or_poc
    value: demo_or_poc
  .properties.telemetry_selector:
    selected_option: disabled
    value: disabled
  .properties.tmc:
    selected_option: disabled
    value: disabled
  .properties.uaa:
    selected_option: internal
    value: internal
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.vm_extensions:
    value:
    - public_ip
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
network-properties:
  network:
    name: PKS-Services
  other_availability_zones:
  - name: pks-az1
  - name: pks-az2
  - name: pks-az3
  service_network:
    name: PKS-Services
  singleton_availability_zone:
    name: pks-az1
resource-config:
  pivotal-container-service:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  pks-db:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsx:
      lbs: []
      security_groups: []
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
errand-config:
  delete-all-clusters:
    pre-delete-state: false
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false