{
 "title": "Application SRE",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "App Name", "query": "label_values(memory, app_name)" },
   { "name": "memChunkSize", "label": "Mem Chunk Size (GB)", "query": "0.5,1,2,4,6,8,12,16" },
   { "name": "diskChunkSize", "label": "Disk Chunk Size (GB)", "query": "0.5,1,2,4,6,8,12,16" }
  ]
 },
 "panels": [
  { "title": "Overall Platform Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 1, "y": 1 },
   "content": "<p>\n<h1><center>CF Push (99.5%)</center></h1>\n</p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 1 },
   "content": "<p>\n<h1><center>App Availability (99.9%)</center></h1>\n</p>"
  },
  {
   "title": "Past Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[1h]) / increase(pas_sli_task_runs_total{task=\"push\"}[1h]))"
    }
   ]
  },
  {
   "title": "Past Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[1d]) / increase(pas_sli_task_runs_total{task=\"push\"}[1d]))"
    }
   ]
  },
  {
   "title": "Past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[30d]) / increase(pas_sli_task_runs_total{task=\"push\"}[30d]))"
    }
   ]
  },
  {
   "title": "Past Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Past Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[30d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CLI Command Status History",
   "type": "stat",
   "description": "## Description\n\nApp Smoke Tests run every 5-minutes. When running HA, multiple smoke tests may run in the given 5-minutes. These tests are intended to give Platform Operators confidence that Application Developers can successfully interact with and manage applications on the platform.\n\nNote: smoke tests will report a failure if any task (e.g. `push`, `login`) takes more than 5 minutes to complete.\n\n## Troubleshooting Steps\n\nIf a failure occurs, attempt to use the failed CLI command in a terminal to see why it is failing. ",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "clamp_min(1 - increase(pas_sli_task_failures_total[10m]),0)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CF Push Duration",
   "type": "graph",
   "description": "CF Push Duration is recorded for every attempted CF push.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(increase(pas_sli_task_duration_seconds_sum{task=\"push\", origin=\"pas-sli-exporter\"}[5m]))",
     "legendFormat": "Time to run the cf push command"
    }
   ]
  },
  {
   "title": "CF Logs Duration",
   "type": "graph",
   "description": "CF Logs Duration is recorded for every attempted CF Log.",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(increase(pas_sli_task_duration_seconds_sum{task=\"logs\", origin=\"pas-sli-exporter\"}[5m]))",
     "legendFormat": "Time to run the cf logs command"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 1, "y": 20 },
   "content": "<p>\n<h1><center>Routing Health</center></h1>\n</p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 13, "y": 20 },
   "content": "<p>\n<h1><center>Container Capacity ($memChunkSize Gb Mem / $diskChunkSize Gb Disk)</center></h1>\n</p>"
  },
  {
   "title": "% of Router Instances Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 1, "y": 22 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"router\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 22 },
   "targets": [
    {
     "expr": "sum(floor((CapacityTotalMemory-CapacityRemainingMemory)/($memChunkSize * 1024)))  < sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024))) or sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024)))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 27 } },
  { "title": "Application Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "App Name - Diego Cell IP - Diego Cell ID",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "memory{job=\"healthwatch-pas-exporter\", app_name=~\"$app_name\"}",
     "legendFormat": "{{app_name}}[{{instance_id}}]   -   {{ip}}   -   {{index}}"
    }
   ]
  }
 ]
}