{
 "title": "GAP Platform SLOs",
 "description": "Service Level Objectives for Tanzu Application Service",
 "time": { "from": "now-28d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(health_check_cliCommand_success, job)"
   },
   {
    "name": "cf_slo",
    "label": "CF Push SLO (%)",
    "query": "0.9, 0.95, 0.99, 0.995, 0.999, 0.9995,0.9999"
   },
   {
    "name": "app_slo",
    "label": "Canary App SLO (%)",
    "query": "0.9, 0.95, 0.99, 0.995, 0.999, 0.9995,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Service Level Objectives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CF Push Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(health_check_cliCommand_success{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "CF Push Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(health_check_cliCommand_success{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(health_check_CanaryApp_available{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s])"
    }
   ]
  },
  {
   "title": "Test App Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 1 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg_over_time(health_check_CanaryApp_available{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "CF Push Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(health_check_cliCommand_success{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $cf_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "Test App Success Error Budget",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(health_check_CanaryApp_available{job=\"$environment\",origin=\"healthwatch\"}[${__range_s}s]) - $app_slo) * ($__range_s / 60)"
    }
   ]
  },
  {
   "title": "SLOs 28 Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CF Push Remaining Error Budget (28 days)",
     "type": "graph",
     "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "# Note: to update your SLO target, change \"0.99\" to your desired uptime percentage and consider updating your alert threshold.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))) - 0.99) * (28 * 24 * 60) ",
       "legendFormat": "{{task}} error budget remaining"
      }
     ]
    },
    {
     "title": "CF Push Remaining Error Budget",
     "type": "stat",
     "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
     "gridPos": { "h": 10, "w": 3, "x": 11, "y": 2 },
     "targets": [
      {
       "expr": "# Note: to update your SLO target, change \"0.99\" to your desired percentage.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))) - 0.99) * (28 * 24 * 60) ",
       "legendFormat": "Error budget remaining"
      }
     ]
    },
    {
     "title": "28-Day Availability",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))"
      }
     ]
    },
    {
     "title": "Canary App Remaining Error Budget (28 days)",
     "type": "graph",
     "description": "## Description\n\nThe amount of time that a canary app (a representative application  running on the platform) can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\nNote: While Healthwatch gathers data over its first 28 days, error budget will slowly increase to reflect availability over the gathered time period.\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "m" }
     ],
     "targets": [
      {
       "expr": "# To change your SLO, update the 0.999 below to your desired availability. \n(avg_over_time(probe_success[28d]) - 0.999) * on(instance) (count_over_time(probe_success[28d]) / 4)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Error Budget Remaining",
     "type": "stat",
     "description": "## Description\n\nThe amount of time that a representative application  running on the platform can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
     "gridPos": { "h": 10, "w": 3, "x": 11, "y": 12 },
     "targets": [
      {
       "expr": "# Note: to update your SLO target, change \"0.999\" to your desired percentage and consider updating your alert threshold.\n(avg_over_time(probe_success[28d]) - 0.999) * on(instance) (count_over_time(probe_success[28d]) / 4)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "28-day Availability",
     "type": "stat",
     "gridPos": { "h": 10, "w": 3, "x": 14, "y": 12 },
     "targets": [
      {
       "expr": "avg_over_time(probe_success[28d])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 22 } }
   ]
  }
 ]
}