{
 "title": "PCF Component Health",
 "description": "% of Running Instances that are Healthy for each PCF Component",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Component",
    "query": "label_values(system_healthy, exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "% of $job instances running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=~\"$job\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  { "title": "Key Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "description": "Diego is a self-healing container management system that attempts to keep the correct number of instances running in Diego cells to avoid network failures and crashes. Diego schedules and runs Tasks and Long-Running Processes (LRP). ",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "content": "<h1><center><a style=\"font-size:100%;color:powderblue;text-decoration:none\" href=\"https://docs.pivotal.io/platform/application-service/concepts/diego/diego-architecture.html\" target=\"_blank\">Diego</a></center></h1>"
  },
  {
   "type": "text",
   "description": "The Cloud Controller in VMware Tanzu Application Service for VMs (TAS for VMs) provides REST API endpoints for clients to access the system. The Cloud Controller maintains a database with tables for orgs, spaces, services, user roles, and more.\n\n\nhttps://docs.pivotal.io/platform/application-service/concepts/architecture/cloud-controller.html",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 4 },
   "content": "\n<h1><center><a style=\"font-size:100%;color:powderblue;text-decoration:none\" href=\"https://docs.pivotal.io/platform/application-service/concepts/architecture/cloud-controller.html\" target=\"_blank\">Cloud Controller</a></center></h1>\n\n\n\n"
  },
  {
   "type": "text",
   "description": "Gorouter routes traffic coming into VMware Tanzu Application Service for VMs (TAS for VMs) to the appropriate component, whether the request comes from an operator addressing the Cloud Controller or from an application user accessing an app running on a Diego Cell. Handling both platform and app requests with the same process centralizes routing logic and simplifies support for WebSocket and other types of traffic (for example, through HTTP CONNECT).\n\nhttps://docs.pivotal.io/platform/application-service/concepts/architecture/router.html",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 4 },
   "content": "\n<h1><center><a style=\"font-size:100%;color:powderblue;text-decoration:none\" href=\"https://docs.pivotal.io/platform/application-service/2-10/routing/index.html\" target=\"_blank\">Routing</a></center></h1>\n\n\n\n"
  },
  {
   "title": "% of Diego Cell instances running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"diego_cell\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of Diego Database instances running",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"diego_database\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of CAPI instances running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"cloud_controller\", origin=\"system_metrics_agent\"})",
     "legendFormat": "cloud_controller"
    },
    {
     "expr": "100 * avg(system_healthy{exported_job=\"cloud_controller_worker\", origin=\"system_metrics_agent\"})",
     "legendFormat": "cloud_controller_worker"
    }
   ]
  },
  {
   "title": "% of Router instances running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"router\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of NATS instances running",
   "type": "stat",
   "description": "NATS is the internal messaging system used by Diego to send messages to the Router in order to register and de-register routes to the cell’s app instances\n\nhttps://docs.pivotal.io/platform/application-service/2-10/concepts/architecture/messaging-nats.html",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"nats\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of Diego Brain instances running",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"diego_brain\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of MySQL instances running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"mysql\", origin=\"system_metrics_agent\"})",
     "legendFormat": "mysql"
    },
    {
     "expr": "100 * avg(system_healthy{exported_job=\"mysql_proxy\", origin=\"system_metrics_agent\"})",
     "legendFormat": "mysql_proxy"
    }
   ]
  },
  {
   "title": "% of UAA instances running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"uaa\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "type": "text",
   "description": "Loggregator gathers and streams logs and metrics from user apps in an Ops Manager deployment. It also gathers and streams metrics from Ops Manager components and health metrics from BOSH-deployed VMs. Loggregator allows you to view these logs and metrics through the Loggregator CLI plugins or through a third-party service.\n\nhttps://docs.pivotal.io/platform/application-service/loggregator/architecture.html",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "content": "<h1><center><a style=\"font-size:100%;color:powderblue;text-decoration:none\" href=\"https://docs.pivotal.io/platform/application-service/loggregator/architecture.html\" target=\"_blank\">Loggregator</a></center></h1>\n"
  },
  {
   "title": "% of Loggregator TC instances running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"loggregator_trafficcontroller\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  {
   "title": "% of Doppler instances running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"doppler\", origin=\"system_metrics_agent\"})"
    }
   ]
  }
 ]
}