{
 "title": "Routing",
 "tags": [ "router" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": " Throughput by Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ngorouter.total_requests\nDescription\nThe requests per minute being served by Gorouter\n\nUse\t\nProvides insight into the overall traffic flow through a deployment. Helps you see trends in the throughput rate that indicate a need to scale the Gorouter.\n\nPossible Next Steps\t\nTo increase throughput and maintain low latency, scale the Gorouters either horizontally or vertically and watch that the system.cpu.user metric for the Gorouter stays in the suggested range of 60-70% CPU Utilization.\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Per Router" }
   ],
   "targets": [
    {
     "expr": "rate(total_requests{exported_job=\"router\", source_id=\"gorouter\"}[1m])",
     "legendFormat": "{{index}}"
    },
    {
     "expr": "sum(rate(total_requests{exported_job=\"router\", source_id=\"gorouter\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "502 Bad Gateways by Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ngorouter.bad_gateways\nDescription\nThe number of bad gateways, or 502 responses, from the Gorouter per minute\n\nUse\t\nIndicates that route tables might be stale. Stale routing tables suggest an issue in the route register management plane, which indicates that something has likely changed with the locations of the containers. Always investigate unexpected increases in this metric.\n\nPossible Next Steps\t\nLook in the Gorouter and route_emitter logs for connection issues to NATS. Check the BOSH logs to see if the NATS, Gorouter, or route_emitter VMs are failing. Look broadly at the health of all VMs, particularly Diego-related VMs. If problems persist, pull Gorouter and route_emitter logs and contact Pivotal Support to say there has been an unusual increase in Gorouter bad gateway responses.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bad_gateways[1m]))",
     "legendFormat": "total 502 errors"
    }
   ]
  },
  {
   "title": "Avg Router Latency",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(latency{exported_job=\"router\"})",
     "legendFormat": "Avg Router latency"
    },
    {
     "expr": "latency{exported_job=\"router\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "All 5XX Errors By Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ngorouter.responses.5xx\nDescription\nThe number of requests completed by the Gorouter VM for HTTP status family 5xx, Server Errors\n\nUse\t\nA repeatedly crashing app is often the cause of a big increase in 5xx responses. However, response issues from apps can also cause an increase in 5xx responses. Always investigate an unexpected increase in this metric.\n\nPossible Next Steps\t\nLook for out-of-memory errors and other app-level errors. As a temporary measure, ensure that a troublesome app is scaled to more than one instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Per Router" }
   ],
   "targets": [
    { "expr": "rate(responses_5xx[1m])", "legendFormat": "{{index}}" },
    { "expr": "sum(rate(responses_5xx[1m]))", "legendFormat": "Total 5xx Errors" }
   ]
  },
  {
   "title": "CPU Utilization By Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nsystem.cpu.user of Gorouter jobs\nDescription\nCPU utilization of the Gorouter.\n\nUse\t\nHigh CPU utilization of the Gorouter VMs can increase latency and cause throughput, or requests per/second, to level-off. Pivotal recommends keeping the CPU utilization within a maximum range of 60-70% for best Gorouter performance.\n\nPossible Next Steps\t\nResolve high utilization by scaling the Gorouters horizontally or vertically by editing the Router VM in the Resource Config pane of the Pivotal Application Service tile.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"router\", unit=\"Load\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Router File Descriptors By Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ngorouter.file_descriptors\nDescription\nThe number of file descriptors currently used by the GoRouter job.\n\nUse\t\nProvides an indication of an impending issue with the GoRouter. Without the proper mitigations, it could be possible for an unresponsive application to eventually exhaust the file descriptors in GoRouter, starving routes from other applications running on PCF. Under heavy load, this unmitigated situation could also result in GoRouter losing its connection to NATS, resulting in all routes being pruned. The GoRouter has a fixed limit at 100,000 file descriptors per job. Once met, the GoRouter will be unable to establish any new connections. To reduce the risk of DDoS, it is advised to implement two possible mitigations: (1) Within Pivotal Application Service, set the\"Max Connections Per Backend\", which manages how many requests can be routed to any particular app instance. This will prevent a single app from using all possible GoRouter connections. The value set here should be determined by the operator based on the use cases for that foundation. As a reference, Pivotal sets this value at 500 for Pivotal Web Services. (2) Add rate limiting at the load balancer level.\n\nPossible Next Steps\t\n(1) Identify which app(s) are requesting excessive connections and resolve the impacting issues with these applications. (2) If above recommended mitigations have not already been taken, do so. (3) Consider adding more GoRouter VM resources to increase available file descriptors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "file_descriptors", "legendFormat": "{{index}}" }
   ]
  },
  {
   "title": "Number of Routes Registered by Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\navg per minute of gorouter.total_routes\nDescription\nThe number of routes registered with the Gorouter\n\nUse\t\nIndicates uptake and gives a picture of the overall growth of the environment for capacity planning. Investigate if the number of routes falls outside of the normal range for your deployment. For example, dramatic increases in the total routes outside of expected business events might point to a denial-of-service attack. Or, dramatic decreases in this metric volume might indicate a problem with the route registration process, such as an app outage or that something in the route register management plane has failed. If there is a problem with the route register management plane, the Time Since Last Route Registered metric should also show to be impacted.\n\nPossible Next Steps\t\nFor capacity needs, scale up or down the Gorouter VMs as necessary. For significant drops in current total routes, see the gorouter.ms_since_last_registry_update metric value for additional context. Look at the Gorouter and route_emitter logs to look for connection issues to NATS. Check the BOSH logs to see if the NATS, Gorouter or route_emitter VMs are failing. Look broadly at the health of all VMs, particularly Diego-related VMs. If problems persist, pull the Gorouter and route_emitter logs and contact Pivotal Support.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(total_routes[1m])", "legendFormat": "{{index}}" }
   ]
  },
  {
   "title": "Route Registration Message Delta",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nper minute aggregated sum of route_emitter.HTTPRouteNATSMessagesEmitted (Registration Messages Sent by Route Emitter) & per minute sum of gorouter.registry_message.route-emitter (Registration Messages Received by GoRouter)\nDescription\nThe registration messages sent metric represents all routing table registration update messages sent by the Diego Route Emitter. This metric in aggregate (across all Route Emitters) represents the total messages sent in given time interval. The registration messages received metric represents the routing table registration update messages received by each Gorouter. Each Gorouter instance should receive all messages sent.\n\nUse\t\nA difference in the rate of change of these metrics is an indication of an issue in the control plane responsible for communicating routing table updates to the Gorouters. An outlier in one or more Gorouter instances, where a Gorouter instances is not aware of all messages sent, can also indicate an issue with that Gorouter instance.\n\nPossible Next Steps\t\nCheck the Gorouter and Route-Emitter logs to see if they are experiencing issues when connecting to NATS. Check the BOSH logs to see if the NATS, Gorouter, or Route-Emitter VMs are failing. Look broadly at the health of all VMs, particularly Diego-related VMs.\nIf problems persist, pull the Gorouter and Route-Emitter logs and contact Pivotal Support.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(RouteRegistration_MessagesDelta[1m])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Router Exhausted Connections By Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ngorouter.backend_exhausted_conns\nDescription\nThe number of requests that have been rejected by the Gorouter VM due to the Max Connections Per Backend limit (how many concurrent TCP connections to any particular app instance) being reached across all backends tried.\n\nUse\t\nIndicates that PCF is mitigating risk to other applications by self-protecting the platform against one or more unresponsive applications. Increases in this metric indicate the need to investigate and resolve issues with potentially unresponsive applications. A rapid rate of change upward is concerning and should be assessed further.\n\nPossible Next Steps\t\nIf Router Exhausted Connections spikes, first look to the Router Throughput to determine if this measure is high or low in relation to normal bounds for this deployment. If Router Throughput appears within normal bounds, it is likely that Router Exhausted Connections is spiking due to an unresponsive application (possibly due to application code issues or underlying application dependency issues). To help determine the problematic application, look in access logs for repeated calls to one application. Then proceed to troubleshoot this application accordingly. If Router Throughput also shows unusual spikes, the cause of the increase in Router Exhausted Connections spikes is likely external to the platform. Unusual increases in load may be due to expected business events driving additional traffic to applications. Unexpected increases in load may indicate a DDoS attack risk.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(backend_exhausted_conns[1m])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Time Since Last Route Registered by Router",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nmax per minute of gorouter.ms_since_last_registry_update\nDescription\nTime in milliseconds since the last route register was received.\n\nUse\t\nIndicates if routes are not being registered to apps correctly. Under normal platform usage, investigate if it has been more than 30 seconds since the Gorouter last received a message from an app.\n\nPossible Next Steps\t\nSearch the Gorouter and route_emitter logs for connection issues to NATS. Check the BOSH logs to see if the NATS, Gorouter, or route_emitter VMs are failing. Look more broadly at the health of all VMs, particularly Diego-related VMs. If problems persist, pull the Gorouter and route_emitter logs and contact Pivotal Support to say there are consistently long delays in route registry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ms_since_last_registry_update", "legendFormat": "{{index}}" }
   ]
  }
 ]
}