---
resource_types:
  - name: concourse-build
    type: docker-image
    check_every: 30m
    source:
      repository: malston/concourse-build-resource
      tag: v0.12.0-rc.9

resources:
  - name: repo
    type: git
    source:
      uri: ((config.uri))
      private_key: ((config.private_key))
      branch: master

  - name: events-install-opsman-logs
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      bucket: ((s3.buckets.logs))
      endpoint: ((s3.endpoint))
      secret_access_key: ((s3_secret_access_key))
      regexp: events-install-opsman-(.*).log
      skip_ssl_verification: true

  - name: events-upgrade-opsman-logs
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      bucket: ((s3.buckets.logs))
      endpoint: ((s3.endpoint))
      secret_access_key: ((s3_secret_access_key))
      regexp: events-upgrade-opsman-(.*).log
      skip_ssl_verification: true

  - name: events-upload-and-stage-pks-logs
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      bucket: ((s3.buckets.logs))
      endpoint: ((s3.endpoint))
      secret_access_key: ((s3_secret_access_key))
      regexp: events-upload-and-stage-pks-(.*).log
      skip_ssl_verification: true

  - name: events-configure-pks-logs
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      bucket: ((s3.buckets.logs))
      endpoint: ((s3.endpoint))
      secret_access_key: ((s3_secret_access_key))
      regexp: events-configure-pks-(.*).log
      skip_ssl_verification: true

  - name: install-opsman-build
    type: concourse-build
    check_every: 30m # try to be neighbourly
    source:
      concourse_url: https://concourse.haas-439.pez.vmware.com
      team: main
      job: install-opsman
      pipeline: deploy-pks-((environment))
      username: admin
      password: password

  - name: upgrade-opsman-build
    type: concourse-build
    check_every: 30m # try to be neighbourly
    source:
      concourse_url: https://concourse.haas-439.pez.vmware.com
      team: main
      job: upgrade-opsman
      pipeline: deploy-pks-((environment))
      username: admin
      password: password

  - name: upload-and-stage-pks-build
    type: concourse-build
    check_every: 30m # try to be neighbourly
    source:
      concourse_url: https://concourse.haas-439.pez.vmware.com
      team: main
      job: upload-and-stage-pks
      pipeline: deploy-pks-((environment))
      username: admin
      password: password
      # initial_build_id: 14

  - name: configure-pks-build
    type: concourse-build
    check_every: 30m # try to be neighbourly
    source:
      concourse_url: https://concourse.haas-439.pez.vmware.com
      team: main
      job: configure-pks
      pipeline: deploy-pks-((environment))
      username: admin
      password: password
      # initial_build_id: 14

  - name: concourse-build-resource # to retrieve utility task YAML
    type: git
    source:
      uri: https://github.com/malston/concourse-build-resource.git
      branch: master

jobs:
  - name: install-opsman-logs
    plan:
      - get: repo
      - get: concourse-build-resource # for task YAML
      - get: install-opsman-build
        trigger: true
        version: every
      # - task: pass-if-the-build-passed
      #   file: concourse-build-resource/tasks/build-pass-fail/task.yml
      #   input_mapping:
      #     build: install-opsman-build
      - task: show-build
        file: concourse-build-resource/tasks/show-build/task.yml
        input_mapping:
          build: install-opsman-build
      - task: show-plan
        file: concourse-build-resource/tasks/show-plan/task.yml
        input_mapping:
          build: install-opsman-build
      - task: show-resources
        file: concourse-build-resource/tasks/show-resources/task.yml
        input_mapping:
          build: install-opsman-build
      - task: show-job
        file: concourse-build-resource/tasks/show-job/task.yml
        input_mapping:
          build: install-opsman-build
      - task: show-logs
        file: concourse-build-resource/tasks/show-logs/task.yml
        input_mapping:
          build: install-opsman-build
      - task: export-logs
        file: repo/tasks/export-logs/task.yml
        input_mapping:
          build: install-opsman-build
        params:
          JOB_NAME: install-opsman
      - put: events-install-opsman-logs
        params:
          file: logs/event*.log

  - name: upgrade-opsman-logs
    plan:
      - get: repo
      - get: concourse-build-resource # for task YAML
      - get: upgrade-opsman-build
        trigger: true
        version: every
      - task: show-build
        file: concourse-build-resource/tasks/show-build/task.yml
        input_mapping:
          build: upgrade-opsman-build
      - task: show-plan
        file: concourse-build-resource/tasks/show-plan/task.yml
        input_mapping:
          build: upgrade-opsman-build
      - task: show-resources
        file: concourse-build-resource/tasks/show-resources/task.yml
        input_mapping:
          build: upgrade-opsman-build
      - task: show-job
        file: concourse-build-resource/tasks/show-job/task.yml
        input_mapping:
          build: upgrade-opsman-build
      - task: show-logs
        file: concourse-build-resource/tasks/show-logs/task.yml
        input_mapping:
          build: upgrade-opsman-build
      - task: export-logs
        file: repo/tasks/export-logs/task.yml
        input_mapping:
          build: upgrade-opsman-build
        params:
          JOB_NAME: upgrade-opsman
      - put: events-upgrade-opsman-logs
        params:
          file: logs/event*.log

  - name: upload-and-stage-pks-logs
    plan:
      - get: repo
      - get: concourse-build-resource # for task YAML
      - get: upload-and-stage-pks-build
        trigger: true
        version: every
      - task: show-build
        file: concourse-build-resource/tasks/show-build/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
      - task: show-plan
        file: concourse-build-resource/tasks/show-plan/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
      - task: show-resources
        file: concourse-build-resource/tasks/show-resources/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
      - task: show-job
        file: concourse-build-resource/tasks/show-job/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
      - task: show-logs
        file: concourse-build-resource/tasks/show-logs/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
      - task: export-logs
        file: repo/tasks/export-logs/task.yml
        input_mapping:
          build: upload-and-stage-pks-build
        params:
          JOB_NAME: upload-and-stage-pks
      - put: events-upload-and-stage-pks-logs
        params:
          file: logs/event*.log

  - name: configure-pks-logs
    plan:
      - get: repo
      - get: concourse-build-resource # for task YAML
      - get: configure-pks-build
        trigger: true
        version: every
      - task: export-logs
        file: repo/tasks/export-logs/task.yml
        input_mapping:
          build: configure-pks-build
        params:
          JOB_NAME: configure-pks
      - put: events-configure-pks-logs
        params:
          file: logs/event*.log

