{
 "title": "Healthwatch - Exporter Troubleshooting",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(scrape_instance_group)"
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Exporter Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"reliabilityView_.*Exporter_status\", scrape_instance_group=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Exporter JVM Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{scrape_instance_group=\"$instance\"}) by (area) / 1e9",
     "legendFormat": "Memory Used - {{area}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{scrape_instance_group=\"$instance\"}) by (area) / 1e9",
     "legendFormat": "Memory Committed - {{area}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_init{scrape_instance_group=\"$instance\"}) by (area) / 1e9",
     "legendFormat": "Initial Memory - {{area}}"
    }
   ]
  },
  {
   "title": "Ephemeral Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "system_disk_ephemeral_percent{exported_job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{scrape_instance_group=\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Rate of Envelope Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"reliabilityView_.*_ingress_envelopes\", scrape_instance_group=\"$instance\"}[5m])",
     "legendFormat": "{{instance}} envelope ingress"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"$instance\"}",
     "legendFormat": "{{instance}} system_cpu_user"
    }
   ]
  },
  {
   "title": "Exporter VM Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{scrape_instance_group=\"$instance\"}",
     "legendFormat": "{{instance}} jvm_threads_current"
    },
    {
     "expr": "jvm_threads_peak{scrape_instance_group=\"$instance\"}",
     "legendFormat": "{{instance}} jvm_threads_peak"
    }
   ]
  }
 ]
}