{
 "title": "PAS MySQL Health - Gap",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "About PAS MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "content": "\n# PAS MySQL Health\n\nThe PAS MySQL database is used for persistent data storage by several PAS components. \n\nNote that this is the SQL database used by system components, not the MySQL service used by applications running on the platform.\n\nPAS components that use system databases include the Cloud Controller, Diego Brain, Gorouter, and User Authorization and Authentication (UAA) server. \n\nFor more information, see [PAS Components](https://docs.pivotal.io/pivotalcf/2-6/concepts/architecture/).\n\n"
    }
   ]
  },
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "PAS MySQL Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 } },
  {
   "title": "PAS MySQL Status History",
   "type": "graph",
   "description": "## Description\n\nRepresents if the MySQL Server is currently responding to requests.\n\nIn single-node mode, if the server does not emit heartbeats, it is offline.\n\n## Troubleshooting Steps\n\nRun mysql-diag and check the MySQL Server logs for errors.",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "0 = unavailable, 1 = available" }
   ],
   "targets": [
    { "expr": "_mysql_available", "legendFormat": "index {{index}}" }
   ]
  },
  {
   "title": "% of MySQL Jobs Reporting Healthy",
   "type": "stat",
   "description": "## Description\n\nRepresents if the MySQL Server is currently responding to requests.\n\nIn single-node mode, if the server does not emit heartbeats, it is offline.\n\n## Troubleshooting Steps\n\nRun mysql-diag and check the MySQL Server logs for errors.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "targets": [
    { "expr": "avg(_mysql_available)", "legendFormat": "{{index}}" }
   ]
  },
  {
   "title": "Troubleshooting Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Galera Cluster Node Readiness",
     "type": "stat",
     "description": "## Description\n\nThe `_mysql_galera_wsrep_ready` metric shows whether each cluster node can accept queries. Returns only 0 or 1. When this metric is 0, almost all queries to that node fail with the error:\n`ERROR 1047 (08501) Unknown Command`\n\nThis panel displays the average of all nodes. When less than 100%, at least one node is down.\n\n## Use\n\nDiscover when nodes of a cluster have been unable to communicate and accept transactions.\n\n## Troubleshooting Steps\n\n1. Run `mysql-diag` and check the MySQL Server logs for errors.\n2. Ensure no infrastructure event is affecting intra-cluster communication.\n3. Ensure that `wsrep_ready` is not set to off by using the query:\n`SHOW STATUS LIKE 'wsrep_ready';`.\n",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
     "targets": [
      { "expr": "avg(_mysql_galera_wsrep_ready)", "legendFormat": "index {{index}}" }
     ]
    },
    {
     "title": "Galera Cluster Status",
     "type": "stat",
     "description": "## Description\n\nShows the primary status of the cluster component that the node is in. Possible values are: Primary = 1 (green), Non-primary = 0 (red), Disconnected = -1 (black)\n\n## Use\n\t\nAny value other than “Primary” indicates that the node is part of a nonoperational component. This occurs in cases of multiple membership changes that result in a loss of quorum.\n\n## Troubleshooting Steps\n\nCheck node status to ensure that they are all in working order and able to receive write-sets. Run mysql-diag and check the MySQL Server logs for errors.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_cluster_status",
       "legendFormat": "index {{index}}"
      }
     ]
    },
    {
     "title": "Galera Cluster Size",
     "type": "stat",
     "description": "## Description\n\nThe number of cluster nodes with which each node is communicating normally.\n\n## Use\n\nWhen running in a multi-node configuration, this metric indicates if each member of the cluster is communicating normally with all other nodes. A calculated value of 3 is healthy. A value less than 3 can indicate that availability is being compromised. A value of less than 1 can indicate the cluster is unavailable.\n\n## Troubleshooting Steps\n\nRun mysql-diag and check the MySQL Server logs for errors.",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "avg(_mysql_galera_wsrep_cluster_size)",
       "legendFormat": "Number of communicating cluster nodes"
      }
     ]
    }
   ]
  }
 ]
}