{
 "title": "UAA",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "About UAA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "content": "# UAA\n\nThe primary role of UAA is as an OAuth2 provider, issuing tokens for client apps to use when they act on behalf of PWS users. In collaboration with the login server, UAA can authenticate users with their PWS credentials, and can act as an SSO service using those, or other, credentials.\n\nUAA has endpoints for managing user accounts and for registering OAuth2 clients, as well as various other management functions.\n\nDifferent runtimes and services use separate UAA instances. PWS has two UAA instances by default: one for BOSH Director, used to bootstrap the rest of the PWS deployment; and one for the BOSH deployment, used as a shared resource by all apps that require user authentication. This is the minimum number of UAA instances PWS must have. Other runtimes and services also have UAA instances. These instances are separate from each other. If you log into one runtime or service, you are not also logged into other runtimes and services that authenticate using UAA. You must log into each runtime or service separately.\n\nFor more details on UAA metrics, visit https://docs.pivotal.io/pivotalcf/2-6/uaa/uaa-metrics.html"
    }
   ]
  },
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "UAA Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 } },
  {
   "title": "UAA Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "0 = unhealthy, 1 = healthy" }
   ],
   "targets": [
    {
     "expr": "system_healthy{exported_job=\"uaa\", origin=\"system_metrics_agent\"}",
     "legendFormat": "UAA Index: {{index}}"
    }
   ]
  },
  {
   "title": "% of UAA Servers Reporting Healthy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"uaa\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  { "title": "Key Performance Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "UAA Request Latency",
   "type": "graph",
   "description": "## Description\n\n95th Percentile latency value of gorouter.latency.uaa. The time in milliseconds that the UAA took to process a request that GoRouter sent to UAA endpoints.\n\n## Use\n\nIndicates how responsive UAA has been to requests sent from the Gorouter. Some operations may take longer amounts of time to process, such as bulk creating users and groups. Unusual spikes in latency could indicate the need to scale the UAA VMs.\n\n## Troubleshooting Steps\n\nLatency is based upon the endpoint and operation being used. It is important to correlate the latency to the endpoint and evaluate latency in the context of the historical latency from that endpoint. First inspect which endpoints requests are hitting. Use historical value to understand if the latency is unusual for that endpoint. A list of UAA endpoints is available as part of the UAA API documentation. If it appears that the UAA needs to scale due to ongoing traffic congestion, do not scale on the latency metric alone. You should also watch that the system.cpu.user metric for the UAA stays in the suggested range of 80-90% maximum CPU Utilization. Resolve high utilization by scaling the UAA VMs horizontally by editing the UAA VM in the Resource Config pane of the PAS tile.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_uaa{source_id=\"gorouter\"}",
     "legendFormat": "Router index: {{index}}"
    }
   ]
  },
  {
   "title": "UAA Requests Exceeding Expected Latency",
   "type": "graph",
   "description": "## Description\n\nNumber of completed requests that exceeded the tolerable response time since last metric emission. Each URL group can have a different tolerable completion time, which is preconfigured in each UAA release. These values are currently not configurable.\n\n## Troubleshooting Steps\n\nIf the number of requests not meeting tolerable completion time is growing, then either the tolerable request time needs to be fine tuned for false negatives, or the server does not have enough capacity to handle the request load. The actual cause for this can be the need for an increase in server or database resources. Further metrics are needed to actually make a scaling decision.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(requests_global_unhealthy_count[5m])",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "UAA CPU Utilization",
   "type": "graph",
   "description": "The percentage of CPU being used on the VM where UAA is deployed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"uaa\",origin=\"system_metrics_agent\"}",
     "legendFormat": "Index: {{index}}"
    }
   ]
  },
  {
   "title": "Memory Utilization on UAA VMs",
   "type": "graph",
   "description": "## Definition\nThe percentage of memory currently being used on the VM where UAA is deployed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{origin=\"system_metrics_agent\", exported_job=\"uaa\"} ",
     "legendFormat": "Index: {{index}}"
    }
   ]
  },
  {
   "title": "Troubleshooting Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed Requests per Minute",
     "type": "graph",
     "description": "## Description\n\nThe number of requests completed by the UAA VM, emitted per UAA instance. Includes all requests sent to the server, including health checks. This chart sums the number of requests each minute.\n\n## Use\n\nUnusually high spikes, if not known to be associated with an expected increase in demand, could indicate a DDoS risk, and should be investigated. For performance and capacity management, look at this metric as either a requests-completed-per-second or requests-completed-per-minute rate to understand the throughput per UAA instance. This helps you see trends in the throughput rate that may indicate a need to scale the UAA instances.\n\n## Troubleshooting Steps\n\nFor optimizing the UAA, consider this metric in the context of UAA Request Latency and UAA VM CPU Utilization. To increase throughput and maintain low latency, scale the UAA VMs horizontally by editing the UAA VM in the Resource Config pane of the PAS tile, and watch that the system.cpu.user metric for the UAA is not sustained in the suggested range of 80-90% maximum CPU Utilization.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(requests_global_completed_count{source_id=\"uaa\"}[1m])",
       "legendFormat": "UAA index: {{index}}"
      }
     ]
    },
    {
     "title": "UAA 500 Errors",
     "type": "graph",
     "description": "Number of HTTP requests that returned 500 codes (server errors) since last metrics emission. \n\nThis metric allows you to calculate error rates and determine if further investigation is needed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(requests_global_status_5xx_count{exported_job=\"uaa\"}[5m])",
       "legendFormat": "Index: {{index}}"
      }
     ]
    }
   ]
  }
 ]
}