{
 "title": "Logging and Metrics Pipeline",
 "description": "Performance of the Logging and Metrics Pipeline (aka Firehose)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About Logging and Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Logging and Metrics\n\nThe Logging and Metrics Firehose (also known as Loggregator) helps gather logs and metrics from across the foundation, to be sent to a number of downstream consumers. \n\nThe health of the components below will dictate whether developers can see logs and metrics for their apps, and whether that information will be sent to tools like Healthwatch, App Metrics and external partners.\n\n(Note: this does not affect platform logs sent over syslog.)"
    }
   ]
  },
  { "title": "Service Level Indicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Firehose Ingress Success Rate",
   "type": "graph",
   "description": "## Description\n\nIndicates whether the foundation's Dopplers are scaled to handle the message load coming from the platform.\n\nExcessive dropped messages can indicate the load coming from the platform exceeds the combined capacity of the Dopplers.\n\n## Troubleshooting Steps\nScale up the number of `doppler` instances.\n\n**Note:** At approximately 40 `doppler` instances and 20 `loggregator_trafficcontroller` instances,\nhorizontal scaling is no longer useful for improving Firehose performance.\nTo improve performance, add vertical scale to the existing `doppler` and\n`loggregator_trafficcontroller` instances by increasing CPU resources.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (100*sum(rate(dropped{source_id=\"doppler\",direction=\"ingress\"}[5m])) / sum(rate(ingress{source_id=\"doppler\"}[5m])))",
     "legendFormat": "% of messages successfully ingressed by dopplers"
    }
   ]
  },
  {
   "title": "Firehose Ingress Success Rate",
   "type": "stat",
   "description": "## Description\n\nIndicates whether the foundation's Dopplers are scaled to handle the message load coming from the platform.\n\nExcessive dropped messages can indicate the load coming from the platform exceeds the combined capacity of the Dopplers.\n\n## Troubleshooting Steps\nScale up the number of `doppler` instances.\n\n**Note:** At approximately 40 `doppler` instances and 20 `loggregator_trafficcontroller` instances,\nhorizontal scaling is no longer useful for improving Firehose performance.\nTo improve performance, add vertical scale to the existing `doppler` and\n`loggregator_trafficcontroller` instances by increasing CPU resources.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
   "targets": [
    {
     "expr": "100 - (100*sum(rate(dropped{source_id=\"doppler\",direction=\"ingress\"}[5m])) / sum(rate(ingress{source_id=\"doppler\"}[5m])))"
    }
   ]
  },
  {
   "title": "Key Performance Indicators for Loggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages per Doppler per Second",
     "type": "graph",
     "description": "## Description\nThis metric indicates the number of messages (logs and metrics) per second emitted by the firehose. The recommended scaling indicator is to look at the average load on the Doppler instances, and increase the number of Doppler instances when the derived rate is 16,000 envelopes per second, or 1 million envelopes per minute.\n\n\n## Troubleshooting Steps\nIncrease the number of `doppler` instances.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ingress{source_id=\"doppler\"}[5m])",
       "legendFormat": "Doppler Index: {{index}}"
      }
     ]
    },
    {
     "title": "Doppler Egress Dropped Messages",
     "type": "graph",
     "description": "## Description\nWithin PAS, logs and metrics enter Loggregator for transport and then egress\nthrough Doppler. Doppler drops messages when consumers of the RLP, such as\nmonitoring tool nozzles, ingest the exiting stream of logs and metrics too slowly.\n\n\n## Troubleshooting Steps\nScale up the number of nozzle instances. The number of nozzle instances should match\nthe number of Traffic Controller instances. You can scale a nozzle using the subscription\nID specified when the nozzle connects to the RLP. If you use the same subscription ID on\neach nozzle instance, the RLP evenly distributes data across all instances of the nozzle.\nFor example, if you have two nozzle instances with the same subscription ID, the RLP sends\nhalf of the data to one nozzle instance and half to the other. Similarly, if you have\nthree nozzle instances with the same subscription ID, the RLP sends one-third of the data\nto each instance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dropped{source_id=\"doppler\", direction=\"egress\"}[5m])",
       "legendFormat": "Doppler Index: {{index}}"
      }
     ]
    },
    {
     "title": "RLP Message Loss Rate",
     "type": "graph",
     "description": "## Description\nExcessive dropped messages can indicate that the RLP is overloaded and\nthat the Traffic Controllers need to be scaled.\n\nThe recommended scaling indicator is to look at the maximum per minute\nloss rate over a 5-minute window and scale if the derived loss rate\nvalue grows greater than `10%`.\n\n\n## Troubleshooting Steps\nScale up the number of log-api instances to further balance log load.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*sum(rate(dropped{source_id=\"reverse_log_proxy\"}[5m])) by (index)\n/sum(rate(ingress{source_id=\"reverse_log_proxy\"}[5m])) by (index)\n",
       "legendFormat": "RLP Index: {{index}}"
      }
     ]
    },
    {
     "title": "RLP Subscriptions",
     "type": "graph",
     "description": "## Description\nWithin PAS, the Reverse Log Proxy (RLP) limits the number of subscriptions.\nA subscription is a consumer of the RLP; this metric concerns the number of\nconcurrent consumers of an RLP instance. The maximum subscription count is 1000\nper RLP.\n\nThis metric indicates that the RLP has reached its concurrent consumer limit.\n\n\n## Troubleshooting Steps\nIncrease the number of RLPs when the average number of `rlp.subscription`s is greater\nthan 900.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(subscriptions{source_id=\"reverse_log_proxy\"}[5m]))"
      }
     ]
    }
   ]
  }
 ]
}