{
 "title": "Canary App Health",
 "description": "State of a representative application running on the foundation",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "blackbox_url", "label": "Canary URL", "query": "probe_success" }
  ]
 },
 "panels": [
  {
   "title": "About Canary App Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Canary App Health\n\nA Canary App is a representative application running on your foundation. The URL of this application is configured in the Healthwatch tile. \n\nThe Canary Health Check is an automated process that uses the Blackbox Exporter to call the configured Canary App URLs and validate successful responses."
    }
   ]
  },
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Canary App Status History",
   "type": "graph",
   "description": "Canary Health uptime check runs once per minute. The results are based on an automated process that calls the configured Canary App and validates a successful response.",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "0 = failure, 1 = success" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=~\"$blackbox_url\", instance!~\"https://opsmgr-02.haas-439.pez.vmware.com\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Canary App Status",
   "type": "stat",
   "description": "Canary Health uptime check runs once per minute. The results are based on an automated process that calls the configured Canary App and validates a successful response. Visualization of results in this graph are based on the health.check.CanaryApp.available metric. This service level indicator is currently configured to test the availability of: Apps Manager",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$blackbox_url\", instance!~\"https://opsmgr-02.haas-439.pez.vmware.com\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Supporting Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Canary App Response Time",
     "type": "graph",
     "description": "The amount of time it took from the initiation of the call to the canary app to the receipt of a success response. The request goes out and back in through the gorouter to measure customer response time and not container-to-container request time. Visualization of results in this graph are based on the health.check.CanaryApp.responseTime metric.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$blackbox_url\", instance!~\"https://opsmgr-02.haas-439.pez.vmware.com\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Canary App HTTP Response Codes",
     "type": "table",
     "description": "## Description\n\nHTTP Status Code for the request made to a given app. The status code can inform where errors are occurring, if there is an issue.\n\n1xx: Information\n\n2xx: Success\n\n3xx: Redirect\n\n4xx: Client Error\n\n5xx: Server Error\n",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$blackbox_url\", instance!~\"https://opsmgr-02.haas-439.pez.vmware.com\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}