{
 "title": "Router",
 "description": "Gorouter routes traffic coming into Cloud Foundry to the appropriate component.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "About Gorouter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Router\n\nGorouter routes traffic coming into Cloud Foundry to the appropriate component, whether the request comes from an operator addressing the Cloud Controller or from an application user accessing an app running on a Diego Cell. \n\n\n\n"
    }
   ]
  },
  { "title": "Service Level Indicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Router Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 } },
  {
   "title": "Router Up",
   "type": "graph",
   "description": "## Description\n\nThe Up metric indicates whether each Router VM is reporting as healthy. \n\n## Troubleshooting Steps\n\nIf a Router VM reports as unhealthy, check detailed metrics below or Router logs.",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_healthy{exported_job=\"router\", origin=\"system_metrics_agent\"}",
     "legendFormat": "Router Index: {{index}}"
    }
   ]
  },
  {
   "title": "% of Router Jobs Running",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "100 * avg(system_healthy{exported_job=\"router\", origin=\"system_metrics_agent\"})"
    }
   ]
  },
  { "title": "Key Performance Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Router CPU Utilization",
   "type": "graph",
   "description": "## Description\nCPU utilization of the Gorouter.\n\n## Use\nHigh CPU utilization of the Gorouter VMs can increase latency and cause throughput, or requests per/second, to level-off. Pivotal recommends keeping the CPU utilization within a maximum range of 60-70% for best Gorouter performance.\n\n## Troubleshooting Steps\t\nResolve high utilization by scaling the Gorouters horizontally or vertically by editing the Router VM in the Resource Config pane of the Pivotal Application Service tile.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"router\", origin=\"system_metrics_agent\"}",
     "legendFormat": "index: {{index}}"
    }
   ]
  },
  {
   "title": "Router File Descriptors",
   "type": "graph",
   "description": "## Definition\nThe number of file descriptors currently used by the GoRouter. Each incoming request to the router consumes 2 file descriptors.\n\n## Use\nProvides an indication of an impending issue with the GoRouter. Without the proper mitigations, it could be possible for an unresponsive application to eventually exhaust the file descriptors in GoRouter, starving routes from other applications running on PCF.\n\n## Possible Next Steps\t\n(1) Identify which app(s) are requesting excessive connections and resolve the impacting issues with these applications. (2) If above recommended mitigations have not already been taken, do so. (3) Consider adding more GoRouter VM resources to increase total available file descriptors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(file_descriptors)",
     "legendFormat": "Greatest number of file descriptors on any single job"
    }
   ]
  },
  {
   "title": "Router 5XX Errors per Minute",
   "type": "graph",
   "description": "## Definition\nRequests per minute completed by the Gorouter VM for HTTP status family 5xx, Server Errors\n\n## Use\nA repeatedly crashing app is often the cause of a big increase in 5xx responses. However, response issues from apps can also cause an increase in 5xx responses. Always investigate an unexpected increase in this metric.\n\n## Possible Next Steps\nLook for out-of-memory errors and other app-level errors. As a temporary measure, ensure that a troublesome app is scaled to more than one instance.\n\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(responses_5xx[1m])", "legendFormat": "index: {{index}}" }
   ]
  },
  {
   "title": "Router Requests per Minute",
   "type": "graph",
   "description": "## Definition\nRequests per minute being served by Gorouter\n\n## Use\nProvides insight into the overall traffic flow through a deployment. Helps you see trends in the throughput rate that indicate a need to scale the Gorouter.\n\n## Possible Next Steps\t\nTo increase throughput and maintain low latency, scale the Gorouters either horizontally or vertically and watch that the system.cpu.user metric for the Gorouter stays in the suggested range of 60-70% CPU Utilization.\n\n\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(total_requests[1m])", "legendFormat": "index :{{index}}" }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router Time Since Last Route Registered",
     "type": "graph",
     "description": "## Definition\nTime  since the last route register was received\n\n## Use\nIndicates if routes are not being registered to apps correctly. Under normal platform usage, investigate if it has been more than 30 seconds since the Gorouter last received a message from an app.\n\n## Possible Next Steps\nSearch the Gorouter and route_emitter logs for connection issues to NATS. Check the BOSH logs to see if the NATS, Gorouter, or route_emitter VMs are failing. Look more broadly at the health of all VMs, particularly Diego-related VMs. If problems persist, pull the Gorouter and route_emitter logs and contact Pivotal Support to say there are consistently long delays in route registry.\n\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "ms_since_last_registry_update", "legendFormat": "index: {{index}}" }
     ]
    }
   ]
  }
 ]
}