{
 "title": "Healthwatch - SLOs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uptime_slo_target",
    "label": "Uptime SLO Target",
    "query": "0.9, 0.95, 0.99, 0.995, 0.999, 0.9995,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-gauge\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Exporter SLO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(\n  sum(\n    0 * absent(service_up{service=\"pas-exporter-gauge\"})\n    or\n    service_up{service=\"pas-exporter-gauge\"}\n  )[${__range_s}s:$__interval]\n)"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min(\n  (\n    avg_over_time(\n      sum(\n        0 * absent(service_up{service=\"pas-exporter-gauge\"})\n        or\n        service_up{service=\"pas-exporter-gauge\"}\n      )[${__range_s}s:$__interval]\n    ) - $uptime_slo_target\n  ) * $__range_s\n  ,\n  0\n)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "$__range_s - (\n  clamp_min(\n    (\n      avg_over_time(\n        sum(\n          0 * absent(service_up{service=\"pas-exporter-gauge\"})\n          or\n          service_up{service=\"pas-exporter-gauge\"}\n        )[${__range_s}s:$__interval]\n      ) - $uptime_slo_target\n    ) * $__range_s\n    ,\n    0\n  )\n)"
    }
   ]
  },
  {
   "title": "Gauge Exporter Up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-gauge\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-counter\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Exporter SLO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(\n  sum(\n    0 * absent(service_up{service=\"pas-exporter-counter\"})\n    or\n    service_up{service=\"pas-exporter-counter\"}\n  )[${__range_s}s:$__interval]\n)"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min(\n  (\n    avg_over_time(\n      sum(\n        0 * absent(service_up{service=\"pas-exporter-counter\"})\n        or\n        service_up{service=\"pas-exporter-counter\"}\n      )[${__range_s}s:$__interval]\n    ) - $uptime_slo_target\n  ) * $__range_s\n  ,\n  0\n)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "$__range_s - (\n  clamp_min(\n    (\n      avg_over_time(\n        sum(\n          0 * absent(service_up{service=\"pas-exporter-counter\"})\n          or\n          service_up{service=\"pas-exporter-counter\"}\n        )[${__range_s}s:$__interval]\n      ) - $uptime_slo_target\n    ) * $__range_s\n    ,\n    0\n  )\n)"
    }
   ]
  },
  {
   "title": "Counter Exporter Up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-counter\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-timer\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Exporter SLO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 34 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(\n  sum(\n    0 * absent(service_up{service=\"pas-exporter-timer\"})\n    or\n    service_up{service=\"pas-exporter-timer\"}\n  )[${__range_s}s:$__interval]\n)"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min(\n  (\n    avg_over_time(\n      sum(\n        0 * absent(service_up{service=\"pas-exporter-timer\"})\n        or\n        service_up{service=\"pas-exporter-timer\"}\n      )[${__range_s}s:$__interval]\n    ) - $uptime_slo_target\n  ) * $__range_s\n  ,\n  0\n)"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 34 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "$__range_s - (\n  clamp_min(\n    (\n      avg_over_time(\n        sum(\n          0 * absent(service_up{service=\"pas-exporter-timer\"})\n          or\n          service_up{service=\"pas-exporter-timer\"}\n        )[${__range_s}s:$__interval]\n      ) - $uptime_slo_target\n    ) * $__range_s\n    ,\n    0\n  )\n)"
    }
   ]
  },
  {
   "title": "Timer Exporter Up",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_up{service=\"pas-exporter-timer\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}