{
 "title": "App Instances",
 "description": "Number and status of Application Instances (AIs) and Tasks running on the platform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About App Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "content": "\n# App Instances\n\nThis dashboard monitors the number and status of Application Instances (AIs) and Tasks running on the platform. \n\nApplication Instances are also referred to as Long-Running Processes (LRPs).\n\nApp Instance and Task metrics help to provide a picture of the current platform utilization, and over time provide insight into growth trends for capacity planning. They are helpful for putting other metrics, such as Router and Logging throughput, in context. \n\nLarge rate of change variations out of traditional environment boundaries should be investigated further."
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Running App Instances",
   "type": "graph",
   "description": "## Description\n\nThe total number of currently running app instances on the platform as reported by Diego.\n\n## Use\n\n\t\nHelps to provide a picture of the current platform utilization, and over time provides insight into growth trends for capacity planning. Helpful for putting other metrics, such as Router and Logging throughput, in context. Large rate of change variations out of traditional environment boundaries should be investigated further.\n\n## Troubleshooting Steps\n\nLarge increases in running app instances due to developer activity indicate the need to scale platform components, such as available cell memory and disk, in response",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LRPsRunning",
     "legendFormat": "Number of app instances running on the platform, as reported by Diego"
    }
   ]
  },
  {
   "title": "Number of App Instances",
   "type": "stat",
   "description": "## Description\n\nThe total number of currently running app instances on the platform as reported by Diego.",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 2 },
   "targets": [
    { "expr": "avg_over_time(LRPsRunning[5m])" }
   ]
  },
  {
   "title": "Troubleshooting: App Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crashed App Instances",
     "type": "graph",
     "description": "## Description\n\nThe total number of app instances that have crashed as reported by Diego.\n\n## Use\t\n\nIndicates how many instances in the deployment are in a crashed state. An unusual increase in this metric can indicate several problems, from a bad app with many instances associated, to a platform issue that is resulting in app crashes.\n\n## Troubleshooting Steps\n\nLook at the BBS logs for apps that are crashing and at the cell logs to see if the problem is with the apps themselves, rather than a platform issue. If the issue cannot be resolved, pull the BBS logs and, if particular apps are the problem, also pull the logs from their Diego cells, and then contact Pivotal Support.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "CrashedActualLRPs", "legendFormat": "Crashed App Instances" }
     ]
    },
    {
     "title": "Auctioneer App Instance Starts",
     "type": "graph",
     "description": "## Description\n\nThe number of app instances that the auctioneer successfully placed on Diego cells.\n\n## Use\t\n\nProvides a sense of running system activity levels in your environment. Can also give you a sense of how many app instances have been started over time. An unexpectedly high level of activity in a short amount of time can indicate container churn.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no app instances being scheduled.\n\n## Troubleshooting Steps\n\nIf observing a significant amount of container churn, look to eliminate explainable causes of temporary churn, such as a deployment or increased developer activity. If container churn appears to continue over an extended period, pull logs from the Diego Brain and BBS node before contacting Pivotal support. When observing extended periods of high or low general activity trends, scale up or down CF components as needed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(AuctioneerLRPAuctionsStarted[5m])",
       "legendFormat": "App instances placed on Diego cells"
      }
     ]
    },
    {
     "title": "Extra App Instances",
     "type": "graph",
     "description": "## Description\n\nTotal number of app instances that are no longer desired but still have a BBS record. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsExtra is the total number of LRP instances that are no longer desired but still have a BBS record.\n\n## Use\t\n\nIf Diego has more LRPs running than expected, there may be problems with the BBS. Deleting an app with many instances can temporarily spike this metric. However, a sustained spike in bbs.LRPsExtra is unusual and should be investigated.\n\n## Troubleshooting Steps\n\nReview the BBS logs for proper operation or errors, looking for detailed error messages. If the condition persists, pull the BBS logs and contact Pivotal Support.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "LRPsExtra",
       "legendFormat": "App instances that are no longer desired but still have a BBS record"
      }
     ]
    },
    {
     "title": "Auctioneer App Instance Placement Failures",
     "type": "graph",
     "description": "## Description\n\nThe number of app instances that the auctioneer failed to place on Diego cells.\n\n## Use\t\n\nThis metric can indicate that PCF is out of container space or that there is a lack of resources within your environment. This indicator also increases when the app instances is requesting an isolation segment, volume drivers, or a stack that is unavailable, either not deployed or lacking insufficient resources to accept the work. This error is most common due to capacity issues, for example, if cells do not have enough resources or if cells are going back and forth between a healthy and unhealthy state.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no app instances being scheduled.\n\n## Troubleshooting Steps\n\nIn order to best determine the root cause, examine the Auctioneer logs. Depending on the specific error and/or resource constraint, you may also find a failure reason in the Cloud Controller(CC) API. Investigate the health of your Diego cells to determine if they are the resource type causing the problem. Consider scaling additional Diego cells. If scaling cells does not solve the problem, pull Diego brain logs and BBS node logs and contact Pivotal Support telling them that LRP auctions are failing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(AuctioneerLRPAuctionsFailed[10m])",
       "legendFormat": "App instances that the auctioneer failed to place on Diego cells"
      }
     ]
    },
    {
     "title": "Missing App Instances",
     "type": "graph",
     "description": "## Description\n\nTotal number of app instances that are desired but have no record in the BBS. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsMissing is the total number of LRP instances that are desired but have no BBS record.\n\n## Use\t\n\nIf Diego has less LRP running than expected, there may be problems with the BBS.\n\n## Troubleshooting Steps\n\nReview the BBS logs for proper operation or errors, looking for detailed error messages. If the condition persists, pull the BBS logs and contact Pivotal Support.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "LRPsMissing",
       "legendFormat": "App Instances tha are desired but have no record in BBS"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting: Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auctioneer Task Placement Failures",
     "type": "graph",
     "description": "## Description\n\nThe number of Tasks that the auctioneer failed to place on Diego cells.\n\n## Use\t\n\nFailing Task auctions indicate a lack of resources within your environment and that you likely need to scale. This indicator also increases when the Task is requesting an isolation segment, volume drivers, or a stack that is unavailable, either not deployed or lacking in sufficient resources to accept the work. This error is most common due to capacity issues, for example, if cells do not have enough resources or if cells are going back and forth between a healthy and unhealthy state.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no app instances being scheduled.\n\n## Troubleshooting Steps\n\nIn order to best determine the root cause, examine the Auctioneer logs. Depending on the specific error and/or resource constraint, you may also find a failure reason in the CC API. Investigate the health of Diego cells. Consider scaling additional Diego cells. If scaling cells does not solve the problem, then pull Diego brain logs and BBS logs for troubleshooting, and contact Pivotal Support telling them that Task auctions are failing.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(AuctioneerTaskAuctionsFailed[10m])",
       "legendFormat": "Tasks that the auctioneer failed to place on Diego cells"
      }
     ]
    },
    {
     "title": "Running Tasks",
     "type": "graph",
     "description": "## Description\n\nThe total number of Tasks running on Diego cells. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "TasksRunning", "legendFormat": "Running Tasks" }
     ]
    },
    {
     "title": "Pending Tasks",
     "type": "graph",
     "description": "## Description\n\nThe total number of Tasks that have not yet been placed on a Diego cell.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "TasksPending", "legendFormat": "Pending Tasks" }
     ]
    }
   ]
  }
 ]
}