{
 "title": "Job Details",
 "description": "System metrics for running jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "health_status",
    "label": "Health Status",
    "query": "All, Unhealthy Only, Healthy Only"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "query_result(system_healthy{origin=\"system_metrics_agent\"} $health_status) "
   },
   {
    "name": "exported_job",
    "label": "BOSH Job",
    "query": "query_result(system_healthy{origin=\"system_metrics_agent\", deployment=~\"$deployment\"} $health_status) "
   },
   {
    "name": "index",
    "label": "VM Index",
    "query": "query_result(system_healthy{origin=\"system_metrics_agent\",exported_job=~\"$exported_job\", deployment=~\"$deployment\"} $health_status ) "
   }
  ]
 },
 "panels": [
  {
   "title": "About Job Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Job Details\n\nJob Health is the most important BOSH-generated metric to monitor. It indicates whether the VM emitting the metric is healthy. \n\nReview this metric across all jobs, and within job grouping, to estimate the overall health of the system.\n\nUse the `Health Status`, `Exported Job`, and `VM Index` filters above to limit your view to particular jobs or VMs, and see detailed VM metrics below."
    }
   ]
  },
  { "title": "Job Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "0: unhealthy, 1: healthy" }
   ],
   "targets": [
    {
     "expr": "system_healthy{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"} $health_status",
     "legendFormat": "{{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "% of Displayed VMs Reporting Healthy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "avg(system_healthy{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "## Description\n\nCPU: high value of `system.cpu.user` reported for this job for the displayed time interval\n\n## Troubleshooting Steps\n\nInvestigate the cause of the spike. If the cause is a normal workload increase, then scale up the affected jobs.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "## Description\n\nMemory: high value of `system.mem.percent` reported for this job for the displayed time interval\n\n## Troubleshooting Steps\n\nThe response depends on the job the metric is associated with. If appropriate, scale affected jobs out and monitor for improvement.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "graph",
   "description": "## Description\n\nSystem Disk: high value of `system.disk.system.percent` reported for this job for the displayed time interval. System disk holds the stemcell binaries, and should remain fairly static in size over the life of the VM.\n\n## Troubleshooting Steps\n\nInvestigate what is filling the job's system partition. This partition should not typically fill because BOSH deploys jobs to use ephemeral and persistent disks.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_system_percent{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Ephemeral Disk Usage",
   "type": "graph",
   "description": "## Description\n\nEphemeral Disk: high value of `system.disk.ephemeral.percent` reported for this job for the displayed time interval. Ephemeral disk holds data that is temporary and will be lost if the VM is recreated.  \n\n## Troubleshooting Steps\n\nRun `bosh vms --details` to view jobs on affected deployments. Determine cause of the data consumption, and, if appropriate, increase disk space or scale out affected jobs.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_ephemeral_percent{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}  {{exported_job}} {{index}}"
    }
   ]
  },
  {
   "title": "Persistent Disk Usage",
   "type": "graph",
   "description": "## Description\n\nPersistent Disk: high value of `system.disk.persistent.percent` reported for this job for the displayed time interval. Persistent Disk holds data meant to be stored long-term. Note that not all jobs use persistent disk.\n\n## Troubleshooting Steps\n\nRun `bosh vms --details` to view jobs on affected deployments. Determine cause of the data consumption, and, if appropriate, increase disk space or scale out affected jobs.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_persistent_percent{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$exported_job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}} {{exported_job}} {{index}}"
    }
   ]
  }
 ]
}