{
 "title": "Diego/Capacity-Gap",
 "description": "The status and capacity of Diego cells on a TAS foundation",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "memChunkSize", "label": "Mem Chunk Size (GB)", "query": "1,2,4,6,8,12,16" },
   { "name": "diskChunkSize", "label": "Disk Chunk Size (GB)", "query": "1,2,4,6,8,12,16" }
  ]
 },
 "panels": [
  {
   "title": "About Diego",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Diego\n\nDiego is a self-healing container management system that attempts to keep the correct number of instances running in Diego cells to avoid network failures and crashes. \n\nDiego schedules and runs Tasks and Long-Running Processes (LRPs). \n\nFor more information about Tasks and LRPs, see [How the Diego Auction Allocates Jobs](https://docs.cloudfoundry.org/concepts/diego/diego-auction.html).\n\n### Chunks\nIn order to stage an application, there must be a sufficient chunk of free memory and disk on a cell. \nFor example, in pushing an app requiring 4GB of memory and 6GB of disk, Diego would have trouble placing that app if there is no one cell with sufficient capacity.\n\n\n"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Diego Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 } },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory: # of [[memChunkSize]]GB Chunks Used",
   "type": "graph",
   "description": "## Description\nThe number of calculated chunks of free memory available, across all cells.\n\n## Use\t\nInsufficient free chunks of memory can prevent pushing and scaling apps. The amount of Free Chunks remaining is a much more valuable indicator of impending cf push errors due to lack of memory than relying on the outputted Memory Remaining metrics alone.\n\nIn order to stage an application, there must be a sufficient chunk of free memory on a cell. For example, in pushing a 4GB app, Diego would have trouble placing that app if there is no one cell with sufficient capacity of 4GB or greater. Pivotal Cloud Ops uses a standard of 4GB, which is the default configuration value provided out-of-the-box. When the number of cells with at least 4GB falls below a desired threshold, this is a scaling indicator to increase capacity. This default 4GB free memory chunk calculation value should be tuned to the the standard size of apps being pushed to this deployment.\n\nNote: A stopped app does not count against used or allocated memory capacity (assuming that any prior AIs were successfully destroyed), because Diego frees the memory and disk allocation it made for that container. The total amount of memory that the Diego cells have allocated is equal to the sum of the memory limit of all started apps * number of instances.\n\n## Possible Next Steps\t\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile. Consider optimizing the size of the cells for the size of a standard app deployment plus overhead. Stopping any non-business-critical apps on the Foundation PAS/Isolation Segment can free up memory without adding resources. If stopping apps does not free up memory chunks, a rebalance could help: `bosh restart` some or all of the cells, that tends to free chunks by clearing out those cells.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(CapacityTotalMemory / ($memChunkSize*1024)))",
     "legendFormat": "Total"
    },
    {
     "expr": "label_replace(\n  sum by (placement_tag)(floor(CapacityTotalMemory / ($memChunkSize*1024)))\n    -\n  sum by (placement_tag)(floor(CapacityRemainingMemory / ($memChunkSize*1024)))\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
     "legendFormat": "{{placement_tag}} Used"
    }
   ]
  },
  {
   "title": "Diego Memory Used / Total",
   "type": "graph",
   "description": "## Description\n\nThe memory used metric indicates the remaining amount of memory available for cells to allocate to their containers.\n\n## Use\n\nLow memory can prevent app scaling and new deployments. The overall sum of capacity can indicate that you need to scale the platform. Pivotal strongly recommends that you have enough memory available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Memory should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "# label replace the empty placement tag to cf\nlabel_replace(\n  (sum by (placement_tag) (CapacityTotalMemory) - sum by (placement_tag) (CapacityRemainingMemory))\n    /\n  sum by (placement_tag) (CapacityTotalMemory)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
     "legendFormat": "{{placement_tag}} % Used"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "expr": "(sum(CapacityTotalMemory)- sum(CapacityRemainingMemory))"
    }
   ]
  },
  {
   "title": "Total Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "targets": [
    { "expr": "sum(CapacityTotalMemory)" }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk: # of [[diskChunkSize]]GB Chunks Used",
   "type": "graph",
   "description": "## Description\n\nThe number of calculated chunks of free disk available, across all cells.\n\n## Use\t\n\nInsufficient free chunks of disk can prevent pushing and scaling apps. The amount of Free Chunks remaining is a much more valuable indicator of impending cf push errors due to lack of disk than relying on the outputted Disk Remaining metrics alone.\n\nIn order to stage an application, there must be a sufficient chunk of free disk on a cell. For example, in pushing a 6GB app, Diego would have trouble placing that app if there is no one cell with sufficient capacity of 6GB or greater. Pivotal Cloud Ops uses a standard of 6GB, which is the default configuration value provided out-of-the-box. When the number of cells with at least 6GB falls below a desired threshold, this is a scaling indicator to increase capacity. This default 6GB free disk chunk calculation value should be tuned to the the standard size of apps being pushed to this deployment.\n\nNote: A stopped app does not count against used or allocated disk capacity (assuming that any prior AIs were successfully destroyed), because Diego frees the memory and disk allocation it made for that container.\n\n## Troubleshooting Steps\n\t\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile. Consider optimizing the size of the cells for the size of a standard app deployment plus overhead (BOSH will allocate 32 GB of disk for swap file). Stopping any non-business-critical apps on the Foundation PAS/Isolation Segment can free up disk without adding resources. If stopping apps does not free up disk, a rebalance could help: `bosh restart` some or all of the cells, that tends to free chunks by clearing out those cells.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(CapacityTotalDisk / ($diskChunkSize*1024)))",
     "legendFormat": "Total"
    },
    {
     "expr": "label_replace(\n  sum by (placement_tag) (floor(CapacityTotalDisk / ($diskChunkSize*1024)))\n    -\n  sum by (placement_tag) (floor(CapacityRemainingDisk / ($diskChunkSize*1024)))\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
     "legendFormat": "{{placement_tag}} Used"
    }
   ]
  },
  {
   "title": "Diego Disk Used / Total",
   "type": "graph",
   "description": "## Description\n\nThe disk used metric indicates the percentage of available disk being used  as a percentage of the total.\n\n## Use\n\t\nLow disk capacity can prevent app scaling and new deployments. The overall sum of capacity can indicate that you need to scale the platform. Pivotal strongly recommends that you have enough disk available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Disk should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  (sum by (placement_tag) (CapacityTotalDisk) - sum by (placement_tag) (CapacityRemainingDisk))\n    /\n  sum by (placement_tag) (CapacityTotalDisk)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
     "legendFormat": "{{placement_tag}} % Used"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "expr": "(sum(CapacityTotalDisk)- sum(CapacityRemainingDisk))"
    }
   ]
  },
  {
   "title": "Total Disk Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "targets": [
    { "expr": "sum(CapacityTotalDisk)" }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Containers",
   "type": "graph",
   "description": "## Description\n\nThe used containers metric indicates the number of containers this cell is using. Unused containers indicates the number of cells remaining to be used on this cell.\n\n## Use\n\nPivotal strongly recommends that you have enough container capacity available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Container Capacity should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(CapacityTotalContainers)", "legendFormat": "Total" },
    {
     "expr": "label_replace(\n  sum by (placement_tag) (CapacityTotalContainers)\n    -\n  sum by (placement_tag) (CapacityRemainingContainers)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
     "legendFormat": "{{placement_tag}} Used"
    }
   ]
  },
  {
   "title": "Containers Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "targets": [
    {
     "expr": "(sum(CapacityTotalContainers)- sum(CapacityRemainingContainers))"
    }
   ]
  },
  {
   "title": "Total Container Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 31 },
   "targets": [
    { "expr": "sum(CapacityTotalContainers)" }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cell Rep Time to Sync",
     "type": "graph",
     "description": "## Description\nTime that the Diego Cell Rep took to sync the ActualLRPs that it claimed with its actual garden containers.\n\n\n## Use\nSync times that are too high compared to normal can indicate issues with the BBS.\n\n\n## Possible Next Steps\t\nInvestigate BBS logs for faults and errors. If a particular cell or cells appear problematic, pull logs for the cells and the BBS logs before contacting Pivotal Support.\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "RepBulkSyncDuration", "legendFormat": "index: {{index}}" }
     ]
    },
    {
     "title": "Route Emitter Time to Sync",
     "type": "graph",
     "description": "## Definition\nTime that the route-emitter took to perform its synchronization pass.\n\n## Use \nIncreases in this metric indicate that the route emitter may have trouble maintaining an accurate routing table to broadcast to the Gorouters. High sync times on this metric can indicate that the BBS may be failing.\n\n## Possible Next Steps\nIf all or many jobs showing as impacted, there is likely an issue with Diego. Investigate the route_emitter and Diego BBS logs for errors. Verify that app routes are functional by making a request to an app, pushing an app and pinging it, or alternatively, validating that the CLI Command Health smoke tests have passed.\n\nIf one or a few jobs showing as impacted, there is likely a connectivity issue and the impacted job should be investigated further.\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "RouteEmitterSyncDuration", "legendFormat": "index: {{index}}" }
     ]
    },
    {
     "title": "Diego & Cloud Controller Synced Check",
     "type": "graph",
     "description": "## Definition\n\nIndicates if the cf-apps Domain is up-to-date, meaning that CF App requests from Cloud Controller are synchronized to bbs.LRPsDesired (Diego-desired AIs) for execution. For this metric, 1 means cf-apps Domain is up-to-date.\n\n## Use \nIf the cf-apps Domain does not stay up-to-date, changes requested in the Cloud Controller are not guaranteed to propagate throughout the system. If the Cloud Controller and Diego are out of sync, then apps running could vary from those desired.\n\n## Troubleshooting Steps\n\nCheck the BBS and Clock Global (Cloud Controller clock) logs. If the problem continues, pull the BBS logs and and Clock Global (Cloud Controller clock) logs and contact Pivotal Support to say that the cf-apps domain is not being kept fresh.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "1 means cf" }
     ],
     "targets": [
      { "expr": "Domain_cf_apps", "legendFormat": "synced check" }
     ]
    }
   ]
  }
 ]
}