{
 "title": "Acme TAS SLOs",
 "description": "Service Level Objectives for Tanzu Application Service",
 "time": { "from": "now-28d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "About Service Level Objectives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Service Level Objectives (SLOs)\n\nService Level Objectives are goals for the quality of service you provide to your customers. \n\nThey are based on Service Level _Indicators_ (SLIs), which are carefully-defined quantitative measures of the service you provide.\n\nHealthwatch has included two sample Service Level Indicators:\n\n\n1. `cf push` Availability, measured by conducting a `cf push` once every 5 minutes.\n2. The uptime of an app running on the platform, measured by periodically pinging the app's URL. This URL is configured in the Healthwatch tile.\n\nThis dashboard alerts based on error budget loss. An alert will fire if the given SLI is losing error budget for a specified period of time. The alert will also fire if error budget reaches zero.\n\nEvery foundation and team is different, and these SLOs and SLIs may not represent the level of service you would like to offer your customers.\n\nIdeas for other SLIs:\n- Canary App response time, measured by the `probe_duration_seconds` metric\n- The availability of a service running on your platform, like MySQL (`_p_mysql_available`) or RabbitMQ (`_p_rabbitmq_haproxy_heartbeat`)\n\nFor more information on SLIs and SLOs, see the [SRE Workbook](https://landing.google.com/sre/workbook/chapters/implementing-slos/) from Google.",
     "targets": [
      { "expr": "probe_success" }
     ]
    }
   ]
  },
  { "title": "Service Level Objectives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "All Alerts",
   "type": "alertlist",
   "description": "This panel displays all alerts configured on this instance of Grafana.",
   "gridPos": { "h": 21, "w": 4, "x": 0, "y": 2 }
  },
  {
   "title": "Contract",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 4, "y": 2 },
   "content": "# CF Push Availability\n\n> An app developer should be able to push an app to the platform using the `cf push` command, with availability of 99%.\n\n\n\n"
  },
  {
   "title": "CF Push Remaining Error Budget (28 days)",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 10, "w": 11, "x": 7, "y": 2 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"0.99\" to your desired uptime percentage and consider updating your alert threshold.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))) - 0.99) * (28 * 24 * 60) ",
     "legendFormat": "{{task}} error budget remaining"
    }
   ]
  },
  {
   "title": "CF Push Remaining Error Budget",
   "type": "stat",
   "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"0.99\" to your desired percentage.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))) - 0.99) * (28 * 24 * 60) ",
     "legendFormat": "Error budget remaining"
    }
   ]
  },
  {
   "title": "28-Day Availability",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 2 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[28d]) / increase(pas_sli_task_runs_total{task=\"push\"}[28d]))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 12 } },
  {
   "title": "Contract",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 4, "y": 13 },
   "content": "# Canary App Availability\n\n> A representative application running on the platform should return a `200` response when pinged, with 99.9% availability.\n\n\n\n"
  },
  {
   "title": "Canary App Remaining Error Budget (28 days)",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that a canary app (a representative application  running on the platform) can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\nNote: While Healthwatch gathers data over its first 28 days, error budget will slowly increase to reflect availability over the gathered time period.\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 10, "w": 11, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "# To change your SLO, update the 0.999 below to your desired availability. \n(avg_over_time(probe_success[28d]) - 0.999) * on(instance) (count_over_time(probe_success[28d]) / 4)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "## Description\n\nThe amount of time that a representative application  running on the platform can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"0.999\" to your desired percentage and consider updating your alert threshold.\n(avg_over_time(probe_success[28d]) - 0.999) * on(instance) (count_over_time(probe_success[28d]) / 4)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "28-day Availability",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 13 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[28d])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}