{
 "title": "Diego Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Diego Total CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (index) (system_cpu_sys{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"} + system_cpu_user{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"} + system_cpu_wait{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "CPU User Utilization%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "System Load - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_1m{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "CPU System Utilization%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sys{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "System Memory %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "Per Diego Cell" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "sum(CapacityAllocatedMemory{exported_job=\"diego_cell\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(CapacityRemainingMemory{exported_job=\"diego_cell\"} + CapacityAllocatedMemory{exported_job=\"diego_cell\"})",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "CPU wait utilization %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_wait{exported_job=\"diego_cell\",origin=\"bosh-system-metrics-forwarder\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Disk for the Cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(CapacityAllocatedDisk{exported_job=\"diego_cell\"})",
     "legendFormat": "Used Disk"
    },
    {
     "expr": "sum(CapacityAllocatedDisk{exported_job=\"diego_cell\"} + CapacityRemainingDisk{exported_job=\"diego_cell\"})",
     "legendFormat": "Total Disk"
    }
   ]
  }
 ]
}