{
 "title": "Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Doppler Average Message Load",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nhealthwatch.Doppler.MessagesAverage.1M\nDescription\nThis derived value represents the average rate of envelopes (messages) per Doppler instance.\n\nUse\t\nIt indicates the need to increase Doppler instances when the existing Doppler instances are at their recommended maximum load.\n\nPossible Next Steps\t\nIncrease the number of Doppler VMs in the Resource Config pane of the Pivotal Application Service (PAS) tile.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Doppler_MessagesAverage_1M", "legendFormat": "{{index}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\ndoppler_proxy.slow_consumer\nDescription\nWithin PAS, metrics and logs enter the Firehose for transport and exit out of the platform via a consumer nozzle. If the consuming downstream system fails to keep up with the exiting stream of metrics, the Firehose is forced to close the connection to protect itself from back-pressure. The Firehose increments this metric with each connection that it closes because a consumer could not keep up.\n\nUse\t\nThis metric indicates that a Firehose consumer, such as a monitoring tool nozzle, is ingesting too slowly. If this number is anomalous, it may result in the downstream monitoring tool not having all expected data, even though that data was successfully transported through the Firehose.\n\nThis can also be confirmed via the Loggregator emitted log message TB: Output channel too full. Dropped N messages, where N is the number of dropped messages.\n\nPossible Next Steps\t\nScale up the number of nozzle instances. You can scale a nozzle using the subscription ID specified when the nozzle connects to the Firehose. If you use the same subscription ID on each nozzle instance, the Firehose evenly distributes data across all instances of the nozzle. For example, if you have two nozzle instances with the same subscription ID, the Firehose sends half of the data to one nozzle instance and half to the other. Similarly, if you have three nozzle instances with the same subscription ID, the Firehose sends one-third of the data to each instance. If you want to scale a nozzle, the number of nozzle instances should match the number of Traffic Controller instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(doppler_proxy_slow_consumer[1m])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Log Transport Loss Rate",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nhealthwatch.Firehose.LossRate.1M\nDescription\nThis derived value represents the loss rate occurring as messages are transported from the Metron Agent components (log ingress point) through the Doppler components to the firehose endpoints. Messages include the combined stream of logs from all apps and the metrics data from Cloud Foundry components.\n\nUse\t\nExcessive dropped messages can indicate the Dopplers are not processing messages fast enough, and that the Doppler instances need to be scaled.\n\nPossible Next Steps\t\nScale up the Firehose log receiver and Dopplers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "Firehose_LossRate_1M{origin=\"healthwatch\"}*100",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Reverse Log Proxy Egress Dropped Messages",
   "type": "graph",
   "description": "Definition\t\nMetrics Used\nrlp.dropped, direction: egress\nDescription\nWithin PAS, logs and metrics enter Loggregator for transport and then egress through the Reverse Log Proxy (RLP). The RLP drops messages when consumers of the RLP, such as monitoring tool nozzles, ingest the exiting stream of logs and metrics too slowly.\n\nUse\t\nThis metric indicates that a consumer of logs and metrics from the RLP, such as a monitoring tool nozzle, is ingesting RLP messages too slowly.\n\nPossible Next Steps\t\nScale up the number of RLP consumers. The number instances for each RLP Consumer should match the number of Trafficcontroller instances. You can scale an RLP Consumer using the subscription ID specified when the consumer connects to the RLP. If you use the same subscription ID on each consumer instance, the RLP evenly distributes data across all instances of the consumers. For example, if you have two consumer instances with the same subscription ID, the RLP sends half of the data to one consumer instance and half to the other. Similarly, if you have three consumer instances with the same subscription ID, the RLP sends one-third of the data to each instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ingestor_dropped", "legendFormat": "{{index}}" }
   ]
  }
 ]
}