{
 "title": "Platform SRE",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "App Name", "query": "label_values(memory, app_name)" },
   { "name": "memChunkSize", "label": "Mem Chunk Size (GB)", "query": "0.5, 1,2,4,6,8,12,16" },
   { "name": "diskChunkSize", "label": "Disk Chunk Size (GB)", "query": "0.5, 1,2,4,6,8,12,16" },
   {
    "name": "cf_slo",
    "label": "CF Push SLO (%)",
    "query": "0.9, 0.95, 0.99, 0.995, 0.999, 0.9995,0.9999"
   },
   {
    "name": "app_slo",
    "label": "Canary App SLO (%)",
    "query": "0.9, 0.95, 0.99, 0.995, 0.999, 0.9995,0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Overall Platform Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 1, "y": 1 },
   "content": "<p>\n<h1><center>CF Push (99.5%)</center></h1>\n</p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 1 },
   "content": "<p>\n<h1><center>App Availability (99.9%)</center></h1>\n</p>"
  },
  {
   "title": "Past Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 1, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[1h]) / increase(pas_sli_task_runs_total{task=\"push\"}[1h]))"
    }
   ]
  },
  {
   "title": "Past Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[1d]) / increase(pas_sli_task_runs_total{task=\"push\"}[1d]))"
    }
   ]
  },
  {
   "title": "Past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "1 - (increase(pas_sli_task_failures_total{task=\"push\"}[30d]) / increase(pas_sli_task_runs_total{task=\"push\"}[30d]))"
    }
   ]
  },
  {
   "title": "Past Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Past Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Past 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[30d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CF Push Remaining Error Budget (30 days)",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"cf_slo\" to your desired uptime percentage and consider updating your alert threshold.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[30d]) / increase(pas_sli_task_runs_total{task=\"push\"}[30d]))) - $cf_slo) * (28 * 24 * 60) ",
     "legendFormat": "{{task}} error budget remaining"
    }
   ]
  },
  {
   "title": "CF Push Remaining Error Budget",
   "type": "stat",
   "description": "## Description\n\nThe amount of time that the `cf push` service can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"$cf_slo\" to your desired percentage.\n((1 - (increase(pas_sli_task_failures_total{task=\"push\"}[30d]) / increase(pas_sli_task_runs_total{task=\"push\"}[30d]))) - $cf_slo) * (28 * 24 * 60) ",
     "legendFormat": "Error budget remaining"
    }
   ]
  },
  {
   "title": "Canary App Remaining Error Budget (30 days)",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that a canary app (a representative application  running on the platform) can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\nNote: While Healthwatch gathers data over its first 28 days, error budget will slowly increase to reflect availability over the gathered time period.\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "# To change your SLO, update the $app_slo below to your desired availability. \n(avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[30d]) - $app_slo) * on(instance) (count_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[28d]) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "App Error Budget Remaining",
   "type": "stat",
   "description": "## Description\n\nThe amount of time that a representative application  running on the platform can be unresponsive or return errors, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect end users, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "# Note: to update your SLO target, change \"$app_slo\" to your desired percentage and consider updating your alert threshold.\n(avg_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[30d]) - $app_slo) * on(instance) (count_over_time(probe_success{instance=\"https://ruby-sample-app.apps.haas-439.pez.vmware.com\"}[30d]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CLI Command Status History",
   "type": "stat",
   "description": "## Description\n\nApp Smoke Tests run every 5-minutes. When running HA, multiple smoke tests may run in the given 5-minutes. These tests are intended to give Platform Operators confidence that Application Developers can successfully interact with and manage applications on the platform.\n\nNote: smoke tests will report a failure if any task (e.g. `push`, `login`) takes more than 5 minutes to complete.\n\n## Troubleshooting Steps\n\nIf a failure occurs, attempt to use the failed CLI command in a terminal to see why it is failing. ",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "clamp_min(1 - increase(pas_sli_task_failures_total[10m]),0)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CF Push Duration",
   "type": "graph",
   "description": "CF Push Duration is recorded for every attempted CF push.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(increase(pas_sli_task_duration_seconds_sum{task=\"push\", origin=\"pas-sli-exporter\"}[5m]))",
     "legendFormat": "Time to run the cf push command"
    }
   ]
  },
  {
   "title": "CF Logs Duration",
   "type": "graph",
   "description": "CF Logs Duration is recorded for every attempted CF Log.",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(increase(pas_sli_task_duration_seconds_sum{task=\"logs\", origin=\"pas-sli-exporter\"}[5m]))",
     "legendFormat": "Time to run the cf logs command"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 25 } },
  {
   "title": "Diego Container Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "graph",
     "description": "## Description\n\nThe used containers metric indicates the number of containers this cell is using. Unused containers indicates the number of cells remaining to be used on this cell.\n\n## Use\n\nPivotal strongly recommends that you have enough container capacity available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Container Capacity should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\n  sum by (placement_tag) (CapacityTotalContainers)\n    -\n  sum by (placement_tag) (CapacityRemainingContainers)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
       "legendFormat": "{{placement_tag}} Used"
      },
      {
       "expr": "sum(floor((CapacityTotalMemory-CapacityRemainingMemory)/($memChunkSize * 1024)))  < sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024))) or sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024)))",
       "legendFormat": "Remaining ($memChunkSize Gb Mem / $diskChunkSize Gb Disk)"
      }
     ]
    },
    {
     "title": "Containers Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "expr": "(sum(CapacityTotalContainers)- sum(CapacityRemainingContainers))"
      }
     ]
    },
    {
     "title": "Remaining ($memChunkSize Gb Mem / $diskChunkSize Gb Disk)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "targets": [
      {
       "expr": "sum(floor((CapacityTotalMemory-CapacityRemainingMemory)/($memChunkSize * 1024)))  < sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024))) or sum(floor((CapacityTotalDisk-CapacityRemainingDisk)/($diskChunkSize * 1024)))"
      }
     ]
    }
   ]
  },
  {
   "title": "Diego Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory: # of [[memChunkSize]]GB Chunks Used",
     "type": "graph",
     "description": "## Description\nThe number of calculated chunks of free memory available, across all cells.\n\n## Use\t\nInsufficient free chunks of memory can prevent pushing and scaling apps. The amount of Free Chunks remaining is a much more valuable indicator of impending cf push errors due to lack of memory than relying on the outputted Memory Remaining metrics alone.\n\nIn order to stage an application, there must be a sufficient chunk of free memory on a cell. For example, in pushing a 4GB app, Diego would have trouble placing that app if there is no one cell with sufficient capacity of 4GB or greater. Pivotal Cloud Ops uses a standard of 4GB, which is the default configuration value provided out-of-the-box. When the number of cells with at least 4GB falls below a desired threshold, this is a scaling indicator to increase capacity. This default 4GB free memory chunk calculation value should be tuned to the the standard size of apps being pushed to this deployment.\n\nNote: A stopped app does not count against used or allocated memory capacity (assuming that any prior AIs were successfully destroyed), because Diego frees the memory and disk allocation it made for that container. The total amount of memory that the Diego cells have allocated is equal to the sum of the memory limit of all started apps * number of instances.\n\n## Possible Next Steps\t\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile. Consider optimizing the size of the cells for the size of a standard app deployment plus overhead. Stopping any non-business-critical apps on the Foundation PAS/Isolation Segment can free up memory without adding resources. If stopping apps does not free up memory chunks, a rebalance could help: `bosh restart` some or all of the cells, that tends to free chunks by clearing out those cells.",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(floor(CapacityTotalMemory / ($memChunkSize*1024)))",
       "legendFormat": "Total"
      },
      {
       "expr": "label_replace(\n  sum by (placement_tag)(floor(CapacityTotalMemory / ($memChunkSize*1024)))\n    -\n  sum by (placement_tag)(floor(CapacityRemainingMemory / ($memChunkSize*1024)))\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
       "legendFormat": "{{placement_tag}} Used"
      }
     ]
    },
    {
     "title": "Diego Memory Used / Total",
     "type": "graph",
     "description": "## Description\n\nThe memory used metric indicates the remaining amount of memory available for cells to allocate to their containers.\n\n## Use\n\nLow memory can prevent app scaling and new deployments. The overall sum of capacity can indicate that you need to scale the platform. Pivotal strongly recommends that you have enough memory available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Memory should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "# label replace the empty placement tag to cf\nlabel_replace(\n  (sum by (placement_tag) (CapacityTotalMemory) - sum by (placement_tag) (CapacityRemainingMemory))\n    /\n  sum by (placement_tag) (CapacityTotalMemory)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
       "legendFormat": "{{placement_tag}} % Used"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "targets": [
      {
       "expr": "(sum(CapacityTotalMemory)- sum(CapacityRemainingMemory))"
      }
     ]
    },
    {
     "title": "Total Memory Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
     "targets": [
      { "expr": "sum(CapacityTotalMemory)" }
     ]
    }
   ]
  },
  {
   "title": "Diego Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk: # of [[diskChunkSize]]GB Chunks Used",
     "type": "graph",
     "description": "## Description\n\nThe number of calculated chunks of free disk available, across all cells.\n\n## Use\t\n\nInsufficient free chunks of disk can prevent pushing and scaling apps. The amount of Free Chunks remaining is a much more valuable indicator of impending cf push errors due to lack of disk than relying on the outputted Disk Remaining metrics alone.\n\nIn order to stage an application, there must be a sufficient chunk of free disk on a cell. For example, in pushing a 6GB app, Diego would have trouble placing that app if there is no one cell with sufficient capacity of 6GB or greater. Pivotal Cloud Ops uses a standard of 6GB, which is the default configuration value provided out-of-the-box. When the number of cells with at least 6GB falls below a desired threshold, this is a scaling indicator to increase capacity. This default 6GB free disk chunk calculation value should be tuned to the the standard size of apps being pushed to this deployment.\n\nNote: A stopped app does not count against used or allocated disk capacity (assuming that any prior AIs were successfully destroyed), because Diego frees the memory and disk allocation it made for that container.\n\n## Troubleshooting Steps\n\t\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile. Consider optimizing the size of the cells for the size of a standard app deployment plus overhead (BOSH will allocate 32 GB of disk for swap file). Stopping any non-business-critical apps on the Foundation PAS/Isolation Segment can free up disk without adding resources. If stopping apps does not free up disk, a rebalance could help: `bosh restart` some or all of the cells, that tends to free chunks by clearing out those cells.",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(floor(CapacityTotalDisk / ($diskChunkSize*1024)))",
       "legendFormat": "Total"
      },
      {
       "expr": "label_replace(\n  sum by (placement_tag) (floor(CapacityTotalDisk / ($diskChunkSize*1024)))\n    -\n  sum by (placement_tag) (floor(CapacityRemainingDisk / ($diskChunkSize*1024)))\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
       "legendFormat": "{{placement_tag}} Used"
      }
     ]
    },
    {
     "title": "Diego Disk Used / Total",
     "type": "graph",
     "description": "## Description\n\nThe disk used metric indicates the percentage of available disk being used  as a percentage of the total.\n\n## Use\n\t\nLow disk capacity can prevent app scaling and new deployments. The overall sum of capacity can indicate that you need to scale the platform. Pivotal strongly recommends that you have enough disk available to suffer a possible failure of an entire availability zone (AZ). If following Pivotal best practice guidance of three AZs, your % Available Disk should always be at least 35%.\n\n## Troubleshooting Steps\n\nAssign more resources to the cells or assign more cells by scaling Diego cells in the Resource Config pane of the Pivotal Application Service tile.",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(\n  (sum by (placement_tag) (CapacityTotalDisk) - sum by (placement_tag) (CapacityRemainingDisk))\n    /\n  sum by (placement_tag) (CapacityTotalDisk)\n  , \"placement_tag\", \"cf\", \"placement_tag\", \"\"\n)",
       "legendFormat": "{{placement_tag}} % Used"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
     "targets": [
      {
       "expr": "(sum(CapacityTotalDisk)- sum(CapacityRemainingDisk))"
      }
     ]
    },
    {
     "title": "Total Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "targets": [
      { "expr": "sum(CapacityTotalDisk)" }
     ]
    }
   ]
  },
  {
   "title": "Routing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 8, "x": 1, "y": 5 },
     "content": "<p>\n<h1><center>Routing Health</center></h1>\n</p>"
    },
    {
     "title": "% of Router Instances Running",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 1, "y": 7 },
     "targets": [
      {
       "expr": "100 * avg(system_healthy{exported_job=\"router\", origin=\"system_metrics_agent\"})"
      }
     ]
    }
   ]
  }
 ]
}