export OM_TARGET="opsmgr-02.${PKS_SUBDOMAIN_NAME}.${PKS_DOMAIN_NAME}"
export OM_USERNAME="${OPSMAN_USER}"
export OM_PASSWORD="${OPSMAN_PASSWORD}"
export OM_DECRYPTION_PASSPHRASE="${OPSMAN_PASSWORD}"
export OM_SKIP_SSL_VALIDATION=true
