{
 "title": "Usage Service",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "About Usage Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "About Usage Service",
     "type": "text",
     "description": "General Information at the Usage Service component.",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "content": "\n## Usage Service\nUsage Service allows for accurate billing of this foundation.\n\n### Overview\nUsage Service tracks the usage of applications, tasks and services pushed to a foundation. Usage Service works by using events generated by the Cloud Controller (CAPI) and then generating Daily, Monthly and Yearly records.\n\n### Deployment\nUsage Service is deployed via a cf pushed errand. \nIt deploys three apps to the System org and space:\n- app-usage-server\n- app-usage-scheduler\n- app-usage-worker\n\n### Usage Service Monitoring\nUsage Service pushes metrics associated with fetching and processing events from Cloud Controller (CAPI.) This is a good way to validate Usage Service is functioning properly.\n\n### General Monitoring Failure\nIf Usage Service is consistently failing, we recommend reaching out to support. In some cases irrecoverable data loss can occur if Usage Service is in a failed state for more than 31 days.\n\n### Usage Service Data\nData generated by Usage Service can be fetched using these [APIs](https://docs.pivotal.io/platform/application-service/operating/accounting-report.html) or via the AppsManger UI.\n\n\n\n"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Usage Service alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 } },
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Usage Service Event Processing Lag",
   "type": "graph",
   "description": "Event Processing Lag displays the time between a usage event being generated in Cloud Controller and when this event is fetched by Usage Service. \nUnder normal conditions, this time should be about one hour. Usage Service has this hour offset to help ensure Cloud Controller events are in the correct states before fetching. \nOccasionally this lag can increase if there are network or Cloud Controller issues.  This occasional, increase lag is fine  as Usage Service will pick up at the last event in Cloud Controller.\n\nIf the lag length approaches 7 day, reach out to support for help. If the lag time length becomes greater than 29 days, data loss may occur. ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Lag Time. 1 Hour Lag Normal." }
   ],
   "targets": [
    {
     "expr": "sum(usage_service_app_usage_event_cc_lag_seconds) by (deployment)",
     "legendFormat": "Processing Lag (deployment: {{deployment}})"
    }
   ]
  },
  {
   "title": "Usage Service Event Fetching Status",
   "type": "graph",
   "description": "Exit Code Results\n\nUsage Service Event fetching runs every time new events are pulled and processed from Cloud Controller. If these Events are processed successfully into Usage Service, the job will emit the Exit Code of 0. If there is an error during event processing then job will emit an Exit Code of 1.\n\nFailures can occur if there is network connectivity issues with other components such as CAPI or UAA. This can occur with regular operation. Usage Service  can handle temporary downtime. If Usage Service recovers with in 29 days there will be no loss in report accuracy.  A longer down time period may result in data loss.\n\nWe recommend that if Usage Service is in a failure state for more than 7 days to reach out to support. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "0 = success, 1 = failure" }
   ],
   "targets": [
    {
     "expr": "sum(usage_service_app_usage_event_fetcher_job_exit_code) by (deployment)",
     "legendFormat": "Apps & Tasks Exit Code (deployment: {{deployment}})"
    },
    {
     "expr": "sum(usage_service_service_usage_event_fetcher_job_exit_code) by (deployment)",
     "legendFormat": "Services Exit Code (deployment: {{deployment}})"
    }
   ]
  },
  { "title": "Supporting Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Usage Service Async Job Failures",
   "type": "graph",
   "description": "Reports on the total number of jobs that have failed.\n\nUsage Service uses a scheduler/worker with delayed jobs architecture. These delayed jobs do all the processing and calculations for Usage Service in background. \n\nThese jobs can fail for a variety of reasons. These failure are generally temporary, in which case Usage Service can recover without data loss or corruption.\n\nIt is expected for this number to grow over time as this system keeps the record of the failed jobs.\n\nIf failures are periodic or ongoing it can signal an issues with the Usage Service system.\n\nThis information can help with diagnostics if others metrics are failing.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Total Historical Job Failures" }
   ],
   "targets": [
    {
     "expr": "sum(usage_service_delayed_job_failures) by (deployment)",
     "legendFormat": "Failures (deployment: {{deployment}})"
    }
   ]
  },
  {
   "title": "Usage Service Events Processed",
   "type": "graph",
   "description": "Usage Service Events Processed displays the respective amount of successfully processed usage events.\nProcessed Events are events that are fetched from CAPI and then processed and stored in Usage Service for use by various later running jobs. This metric is a good indicator that Usage Service is running correctly as it is the first step in Usage Service tracking this Foundations usage.\n\nFor active Foundation, expect to see a lot of activity. For inactive Foundation, expect little activity. \n\nIf you notice little or no activity on this chart in an active Foundation, it could indicate an issue with Usage Service.  If you think this is happening for more than 7 day, reach out to support.\n\nIf Usage Service is in a failed state for more than 29 days, data loss may occur.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    {
     "format": "short",
     "label": "Count of Events Successfully Processed"
    }
   ],
   "targets": [
    {
     "expr": "sum(usage_service_app_usage_event_fetcher_job_processed_app_events) by (deployment)",
     "legendFormat": "App Events Processed (deployment: {{deployment}})"
    },
    {
     "expr": "sum (usage_service_app_usage_event_fetcher_job_processed_task_events) by (deployment)",
     "legendFormat": "Task Events Processed (deployment: {{deployment}})"
    },
    {
     "expr": "sum(usage_service_service_usage_event_fetcher_job_processed_events) by (deployment)",
     "legendFormat": "Service Events Processed (deployment: {{deployment}})"
    }
   ]
  }
 ]
}