apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mde-application-developer
  namespace: mde-application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s-dev-developer
