apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
- apiGroups:
  - apps
  - autoscaling
  - ""
  - certificates.k8s.io
  - batch
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - configmaps
  - endpoints
  - events
  - horizontalpodautoscalers
  - pods
  - pods/log
  - pods/exec
  - podtemplates
  - replicationcontrollers
  - secrets
  - services
  - services/proxy
  - persistentvolumeclaims
  - certificatesigningrequests
  - cronjobs
  - jobs
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  - ""
  - storage.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  - clusterroles
  - serviceaccounts
  - roles
  - resourcequotas
  - namespaces
  - persistentvolumes
  - storageclasses
  verbs:
  - get
  - list
