platform: linux

image_resource:
  type: docker-image
  source:
    repository: malston/concourse-build-resource
    tag: v0.12.0-rc.7

inputs:
- name: repo
- name: build

outputs:
- name: logs

params:
  JOB_NAME:

run:
  path: repo/tasks/export-logs/task.sh
