{
 "title": "Kubernetes Scheduler",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "query_result(workqueue_adds_total{cluster!=\"\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(process_cpu_seconds_total{job=~\".*-kube-scheduler\", cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About Kubernetes Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Kubernetes Scheduler\n\nkube-scheduler is the default scheduler for Kubernetes and runs as part of the control plane. kube-scheduler is designed so that, if you want and need to, you can write your own scheduling component and use that instead.\n\nFor every newly created pod or other unscheduled pods, kube-scheduler selects an optimal node for them to run on. However, every container in pods has different requirements for resources and every pod also has different requirements. Therefore, existing nodes need to be filtered according to the specific scheduling requirements.\n\nIn a cluster, Nodes that meet the scheduling requirements for a Pod are called feasible nodes. If none of the nodes are suitable, the pod remains unscheduled until the scheduler is able to place it.\n\nThe scheduler finds feasible Nodes for a Pod and then runs a set of functions to score the feasible Nodes and picks a Node with the highest score among the feasible ones to run the Pod. The scheduler then notifies the API server about this decision in a process called binding.\n\nFactors that need taken into account for scheduling decisions include individual and collective resource requirements, hardware / software / policy constraints, affinity and anti-affinity specifications, data locality, inter-workload interference, and so on.\n\n\nFor more information, see the [documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/)\n\n\n\n"
    }
   ]
  },
  { "title": "Scheduler Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "% Schedulers Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg(up{job=~\"($cluster)-kube-scheduler\"})"
    }
   ]
  },
  {
   "title": "Scheduler Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"([[cluster]])-kube-scheduler\", instance=~\"($instance)\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "ErrorBudget (28d) > 99.000",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that the Kubernetes Scheduler can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max((avg_over_time(up{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[28d]) - 0.99) * (28 * 24 * 60) * 60) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Scheduler Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\", verb=\"GET\"}[5m])) by (cluster, instance, verb, url, le))",
     "legendFormat": "{{cluster}} {{instance}} {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Operations Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(scheduler_e2e_scheduling_duration_seconds_count{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[5m])) by (cluster, instance)*60",
     "legendFormat": "{{cluster}} {{instance}} e2e"
    },
    {
     "expr": "max(rate(scheduler_binding_duration_seconds_count{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[5m])) by (cluster, instance)*60",
     "legendFormat": "{{cluster}} {{instance}} binding"
    },
    {
     "expr": "max(rate(scheduler_scheduling_algorithm_duration_seconds_count{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[5m])) by (cluster, instance)*60",
     "legendFormat": "{{cluster}} {{instance}} scheduling algorithm"
    },
    {
     "expr": "max(rate(scheduler_volume_scheduling_duration_seconds_count{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[5m])) by (cluster, instance)*60",
     "legendFormat": "{{cluster}} {{instance}} volume"
    }
   ]
  },
  {
   "title": "Scheduler Results per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_schedule_attempts_total{cluster=\"$cluster\"}[5m])*60",
     "legendFormat": "{{cluster}} {{instance}} {{result}}"
    }
   ]
  },
  {
   "title": "API Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(rest_client_requests_total{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\",code=~\"2..\"}[5m])) by (cluster, instance) *60",
     "legendFormat": "{{cluster}} {{instance}} 2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\",code=~\"3..\"}[5m])) by (cluster, instancence) *60",
     "legendFormat": "{{cluster}} {{instance}} 3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\",code=~\"4..\"}[5m])) by (cluster, instancence) *60",
     "legendFormat": "{{cluster}} {{instance}} 4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\",code=~\"5..\"}[5m])) by (cluster, instance) *60",
     "legendFormat": "{{cluster}} {{instance}} 5xx"
    }
   ]
  },
  { "title": "Process Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"($cluster)-kube-scheduler\", instance=~\"($instance)\"}[5m])",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"($cluster)-kube-scheduler\",instance=~\"($instance)\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  }
 ]
}