{
 "title": "Kubernetes Controller Manager",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "query_result(workqueue_adds_total{cluster!=\"\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(process_cpu_seconds_total{job=~\".*-kube-controller-manager\", cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About Controller Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "content": "# Kubernetes Controller Manager\n\nThe Kubernetes controller manager\nis a daemon that embeds the core control loops shipped with Kubernetes.\nIn applications of robotics and automation,\na control loop is a non-terminating loop that regulates the state of the system.\nIn Kubernetes,\na controller is a control loop that watches the shared state of the cluster through the apiserver\nand makes changes attempting to move the current state towards the desired state.\nExamples of controllers that ship with Kubernetes today are\nthe replication controller, endpoints controller, namespace controller, and serviceaccounts controller.\n\n\nFor more information, visit kube-controller-manager [documentation](https://kubernetes.io/docs/concepts/overview/components/#kube-controller-manager)."
    }
   ]
  },
  { "title": "Controller Manager Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "% Controller Managers Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg by (cluster) (up{job=~\"([[cluster]])-kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Controller Manager Instance Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"([[cluster]])-kube-controller-manager\", instance=~\"($instance)\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"([[cluster]])-kube-controller-manager\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"([[cluster]])-kube-controller-manager\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"([[cluster]])-kube-controller-manager\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"([[cluster]])-kube-controller-manager\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"([[cluster]])-kube-controller-manager\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"([[cluster]])-kube-controller-manager\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=~\"([[cluster]])-kube-controller-manager\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=~\"([[cluster]])-kube-controller-manager\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"([[cluster]])-kube-controller-manager\"}[5m])) by (name, le))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Process Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"([[cluster]])-kube-controller-manager\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"([[cluster]])-kube-controller-manager\"}[5m])",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"([[cluster]])-kube-controller-manager\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  }
 ]
}