{
 "title": "Kubernetes API Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(apiserver_request_total{job=~\"([[cluster]])-kubernetes-apiservers\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About Kubernetes API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Kubernetes API Server\n\nThe API server is a component of the Kubernetes control plane that exposes the Kubernetes API. The API server is the front end for the Kubernetes control plane.\n\nThe main implementation of a Kubernetes API server is\n[kube-apiserver](https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver).\nkube-apiserver is designed to scale horizontally—that is, it scales by deploying more instances.\nYou can run several instances of kube-apiserver and balance traffic between those instances.\n\n"
    }
   ]
  },
  { "title": "API Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "% API Servers Up",
   "type": "stat",
   "description": "## Description\n\nThis displays the percentage of healthy API Servers in the selected cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg by (cluster) (up{job=~\"([[cluster]])-kubernetes-apiservers\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "API Server Instance Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"([[cluster]])-kubernetes-apiservers\", instance=~\"($instance)\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "ErrorBudget (28d) > 99.000",
   "type": "graph",
   "description": "## Description\n\nThe amount of time that the Kubernetes API Server can be down, while still meeting the SLO target. Error budget is calculated over a rolling 28-day window (28 days ago until now).\n\n## Use\n\nIn addition to identifying issues that affect users of the platform, this error budget helps operators to plan maintenance, upgrades, and other activities that cause downtime.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max((avg_over_time(up{job=~\"($cluster)-kubernetes-apiservers\", instance=~\"($instance)\"}[28d]) - 0.99) * (28 * 24 * 60) * 60) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "2xx Response Codes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=~\"([[cluster]])-kubernetes-apiservers\", instance=~\"$instance\",code=~\"2..\"}[5m])) by (job)",
     "legendFormat": "2xx {{job}}"
    }
   ]
  },
  {
   "title": "4xx Response Codes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=~\"([[cluster]])-kubernetes-apiservers\", instance=~\"$instance\",code=~\"4..\"}[5m])) by (job)",
     "legendFormat": "4xx {{job}}"
    }
   ]
  },
  {
   "title": "5xx Response Codes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=~\"([[cluster]])-kubernetes-apiservers\", instance=~\"$instance\",code=~\"5..\"}[5m])) by (job)",
     "legendFormat": "5xx {{job}}"
    }
   ]
  },
  {
   "title": "API Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=~\"($cluster)-kubernetes-apiservers\", instance=~\"($instance)\"}[5m])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "API Errors ",
   "type": "graph",
   "description": "## Description\n\nPercentage of API Server requests that return a 5xx error code.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource, job, instance) (rate(apiserver_request_total{job=~\"($cluster)-kubernetes-apiservers\", instance=~\"($instance)\", code=~\"5..\"}[5m])) / sum by (resource, job, instance) (rate(apiserver_request_total{job=~\"($cluster)-kubernetes-apiservers\", instance=~\"($instance)\"}[5m]))",
     "legendFormat": "{{job}} {{instance}} {{ resource }}"
    }
   ]
  },
  { "title": "Process Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"([[cluster]])-kubernetes-apiservers\",instance=~\"$instance\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"([[cluster]])-kubernetes-apiservers\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"([[cluster]])-kubernetes-apiservers\",instance=~\"$instance\"}",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  }
 ]
}