{
 "title": "Kubernetes Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(etcd_server_has_leader, cluster_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(etcd_server_has_leader{cluster_name=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "About Kubernetes Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Kubernetes Etcd\n\n`etcd` is a consistent and highly-available key value store used as Kubernetes’ backing store for all cluster data.\n\nFor more information, see [documentation](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/)\n\n\n"
    }
   ]
  },
  { "title": "Key Performance Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "max by (cluster) (etcd_server_has_leader{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{cluster_name=~\"$cluster\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  { "title": "Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(rate(etcd_server_proposals_failed_total{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} Proposal Failure Rate"
    },
    {
     "expr": "sum by (cluster)(etcd_server_proposals_pending{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{cluster}} Proposal Pending Total"
    },
    {
     "expr": "sum by (cluster)(rate(etcd_server_proposals_committed_total{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} Proposal Commit Rate"
    },
    {
     "expr": "sum by (cluster)(rate(etcd_server_proposals_applied_total{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(etcd_server_proposals_pending{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{cluster}} Proposals pending"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(rate(etcd_server_proposals_committed_total{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} total number of consensus proposals committed"
    },
    {
     "expr": "sum by (cluster)(rate(etcd_server_proposals_applied_total{cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster_name=~\"$cluster\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  { "title": "Etcd Detail Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (rate(grpc_server_started_total{grpc_type=\"unary\", cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} RPC Rate"
    },
    {
     "expr": "sum by (cluster) (rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\", cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\", cluster_name=~\"$cluster\"}) - sum by (cluster)(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\", cluster_name=~\"$cluster\"})",
     "legendFormat": "{{cluster}} Watch Streams"
    },
    {
     "expr": "sum by (cluster)(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\", cluster_name=~\"$cluster\"}) - sum by (cluster)(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\", cluster_name=~\"$cluster\"})",
     "legendFormat": "{{cluster}} Lease Streams"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{cluster_name=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{cluster_name=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(rate(etcd_debugging_snap_save_total_duration_seconds_sum{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster_name=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{cluster_name=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster_name=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster_name=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(rate(etcd_disk_wal_fsync_duration_seconds_sum{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} latency distributions of fsync called by wal"
    },
    {
     "expr": "sum by (cluster)(rate(etcd_disk_backend_commit_duration_seconds_sum{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster)(rate(etcd_network_client_grpc_received_bytes_total{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} total number of bytes received by grpc clients"
    },
    {
     "expr": "sum by (cluster)(rate(etcd_network_client_grpc_sent_bytes_total{cluster_name=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} total number of bytes sent to grpc clients"
    }
   ]
  }
 ]
}