{
 "title": "PKS Control Plane",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "About PKS Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "content": "\n# PKS Control Plane\n\nAn Enterprise PKS environment consists of a PKS Control Plane and one or more workload clusters.\n\nEnterprise PKS administrators use the PKS Control Plane to deploy and manage Kubernetes clusters. The workload clusters run the apps pushed by developers.\n\nFor more information see [PKS Architecture](https://docs.pivotal.io/pks/1-7/control-plane.html)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "type": "alertlist", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 } }
   ]
  },
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "PKS SLI Tests",
   "type": "graph",
   "description": "This panel graphs the results of the PKS SLI Test Exporter.  If the Failure rate is above zero then the operator will want to begin troubleshooting by checking the logs for the PKS SLI Exporter to see why the test is failing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "0 = failure, 1 = success" }
   ],
   "targets": [
    {
     "expr": "clamp_min(1-increase(pks_sli_task_failures_total[2m]), 0)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "PKS SLI Tests Latency",
   "type": "graph",
   "description": "This panel graphs the results of the PKS SLI Test Exporter. If latency is unusually high, look into the PKS API vm and PKS DB vm health.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_sli_task_run_duration_seconds",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(pks_sli_task_failures_total{task=\"login\"}[2m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "increase(pks_sli_task_failures_total{task=\"clusters\"}[2m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "increase(pks_sli_task_failures_total{task=\"get-credentials\"}[2m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "increase(pks_sli_task_failures_total{task=\"plans\"}[2m])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "targets": [
    { "expr": "pks_sli_number_of_clusters", "legendFormat": "Num Clusters" }
   ]
  },
  { "title": "VM Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PKS API Health",
   "type": "stat",
   "description": "## Description\nThis is the most important BOSH metric to monitor. It indicates if the VM emitting the metric is healthy. Review this metric for all VMs to estimate the overall health of the system.\n\nMultiple unhealthy VMs signals problems with the underlying IAAS layer.\n\n## Troubleshooting Steps\nInvestigate the PKS logs for the unhealthy component.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "system_healthy{exported_job=~\"pivotal-container-service\"}"
    }
   ]
  },
  {
   "title": "PKS DB Health",
   "type": "stat",
   "description": "## Description\nThis is the most important BOSH metric to monitor. It indicates if the VM emitting the metric is healthy. Review this metric for all VMs to estimate the overall health of the system.\n\nMultiple unhealthy VMs signals problems with the underlying IAAS layer.\n\n## Troubleshooting Steps\nInvestigate the PKS logs for the unhealthy component.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "system_healthy{exported_job=~\"pks-db\"}"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "graph",
   "description": "## Description\nThis is the most important BOSH metric to monitor. It indicates if the VM emitting the metric is healthy. Review this metric for all VMs to estimate the overall health of the system.\n\nMultiple unhealthy VMs signals problems with the underlying IAAS layer.\n\n## Troubleshooting Steps\nInvestigate the PKS logs for the unhealthy component.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_healthy{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}} "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "## Description\n\nCPU: high value of `system_cpu_user` reported for this job for the displayed time interval\n\n## Troubleshooting Steps\n\nInvestigate the cause of the spike. If the cause is a normal workload increase, then scale up the affected VM(s) vertically.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "## Description\n\nMemory: high value of `system_mem_percent` reported for this job for the displayed time interval\n\n## Troubleshooting Steps\n\nThe response depends on the job the metric is associated with. If appropriate, scale affected jobs out and monitor for improvement.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "graph",
   "description": "## Description\n\nSystem Disk: high value of `system_disk_system_percent` reported for this job for the displayed time interval. System disk holds the stemcell binaries, and should remain fairly static in size over the life of the VM.\n\n## Troubleshooting Steps\n\nInvestigate what is filling the job's system partition. This partition should not typically fill because BOSH deploys jobs to use ephemeral and persistent disks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_system_percent{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Ephemeral Disk Usage",
   "type": "graph",
   "description": "## Description\n\nEphemeral Disk: high value of `system_disk_ephemeral_percent` reported for this job for the displayed time interval. Ephemeral disk holds data that is temporary and will be lost if the VM is recreated.  \n\n## Troubleshooting Steps\n\nRun `bosh vms --vitals` to view jobs on affected deployments. Determine cause of the data consumption, and, if appropriate, increase disk space or scale out affected jobs.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_ephemeral_percent{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Persistent Disk Usage",
   "type": "graph",
   "description": "## Description\n\nPersistent Disk: high value of `system_disk_persistent_percent` reported for this job for the displayed time interval. Persistent Disk holds data meant to be stored long-term. Note that not all jobs use persistent disk.\n\n## Troubleshooting Steps\n\nRun `bosh vms --vitals` to view jobs on affected deployments. Determine cause of the data consumption, and, if appropriate, increase disk space or scale out affected jobs.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_persistent_percent{exported_job=~\"pivotal-container-service|pks-db\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  { "title": "All Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Master VMs Health Status",
   "type": "stat",
   "description": "## Description\nThis is the most important BOSH metric to monitor. It indicates if the Master VMs are healthy.\n\n## Troubleshooting Steps\nFind out which Master VM(s) are unhealthy.  Use the BOSH cli to find out which processes are unhealthy and investigate the logs for those processes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg(system_healthy{exported_job=\"master\"})"
    }
   ]
  },
  {
   "title": "Worker VMs Health Status",
   "type": "stat",
   "description": "## Description\nThis is the most important BOSH metric to monitor. It indicates if the Worker VMs are healthy.\n\n## Troubleshooting Steps\nFind out which Worker VM(s) are unhealthy.  Use the BOSH cli to find out which processes are unhealthy and investigate the logs for those processes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "avg(system_healthy{exported_job=\"worker\"})"
    }
   ]
  }
 ]
}